/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riwayat;

import ukk.pelapor.*;
import ukk.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.swing.JRViewer;
import ukk.session;


/**
 *
 * @author dppra
 */
public class datapengaduan extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    String pathFoto = null;

 
    private DefaultTableModel model;
    
    
    public datapengaduan() {
        initComponents();
        setLocationRelativeTo(null);// membuat tengah form
        conn = Koneksi.Koneksi.KoneksiDB();
        model = new DefaultTableModel();
        jTable1.setModel(model);

       // tampilIdPengaduan();

       // getData();//javaConnect = nama file || Connection = nama method
        
        
        //memberi penamaan pada judul kolom ; 
        model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("id pengaduan");
        model.addColumn("nik");
        model.addColumn("nama");
        model.addColumn("Tanggal Pengaduan");
        model.addColumn("Isi Laporan");
        model.addColumn("Foto");
        model.addColumn("Kategori");
        model.addColumn("lokasi");
        model.addColumn("Status");
        
        
        
        getData();//memanggil method getdata
       }
    //menampilkan data kejTabel1
    void getData() {
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
       
    
    try {
        String sql = "SELECT * FROM pengaduan";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();

        
        //penelusuran baris pada table surat_masuk dari database
        while (rs.next()) {
            Object[] obj = new Object[9];
            obj[0] = rs.getString("id_pengaduan");
            obj[1] = rs.getString("nik");
            obj[2] = rs.getString("nama");
            obj[3] = rs.getString("tgl_pengaduan");
            obj[4] = rs.getString("isi_laporan");
            obj[5] = rs.getString("foto");
            obj[6] = rs.getString("Kategori");
            obj[7] = rs.getString("lokasi");
            obj[8] = rs.getString("status");
            
            model.addRow(obj);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);      
    }
}

    void bersih() {
     //  txt_pengaduan.setText("");
       txt_cari.setText("");
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        filtter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmb_kategori = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        lbl_total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PENGADUAN");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("refresh");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 50, 20));

        jButton7.setText("exit");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 50, 20));

        filtter.setText("filter");
        filtter.setBorder(null);
        filtter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtterActionPerformed(evt);
            }
        });
        jPanel1.add(filtter, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 60, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 590, 290));

        cmb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sarana", "Prasarana" }));
        cmb_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_kategoriActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 110, 20));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 130, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 120, -1));

        jLabel1.setText("Sampai");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel2.setText("Dari");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 340, -1));

        lbl_total.setText("TOTAL:");
        jPanel1.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtterActionPerformed
        if (jDateChooser1.getDate() == null || jDateChooser2.getDate() == null) {
         JOptionPane.showMessageDialog(this, "Silakan pilih rentang tanggal!");
         return; }

        DefaultTableModel modelBaru = new DefaultTableModel();
        modelBaru.addColumn("ID Pengaduan");
        modelBaru.addColumn("NIK");
        modelBaru.addColumn("Nama");
        modelBaru.addColumn("Tanggal");
        modelBaru.addColumn("Isi Laporan");
        modelBaru.addColumn("Foto");
        modelBaru.addColumn("Kategori");
        modelBaru.addColumn("Lokasi");
        modelBaru.addColumn("Status");

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dari = sdf.format(jDateChooser1.getDate());
            String sampai = sdf.format(jDateChooser2.getDate());

            String sql = "SELECT * FROM pengaduan WHERE tgl_pengaduan BETWEEN ? AND ? ORDER BY tgl_pengaduan ASC";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, dari);
            pst.setString(2, sampai);

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                modelBaru.addRow(new Object[]{
                    rs.getString("id_pengaduan"),
                    rs.getString("nik"),
                    rs.getString("nama"),
                    rs.getString("tgl_pengaduan"),
                    rs.getString("isi_laporan"),
                    rs.getString("foto"),
                    rs.getString("Kategori"),
                    rs.getString("lokasi"),
                    rs.getString("status")
                });
            }

            jTable1.setModel(modelBaru);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal filter: " + e.getMessage());
        }

         // TODO add your handling code here:
    }//GEN-LAST:event_filtterActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       ukk.menu.menuAdmin menu = new ukk.menu.menuAdmin();
    
    // 2. Menampilkan Menu Admin
    menu.setVisible(true);
    
    // 3. Menutup halaman Riwayat Aspirasi saat ini
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          try {
        // 1️⃣ Hapus input tanggal
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);

        // 2️⃣ Bersihkan field input lainnya (opsional)
        bersih(); // ini membersihkan txt_nik, txt_nama, txt_isi, lokasi, foto, dll

        // 3️⃣ Refresh tabel dengan semua data (tanpa filter tanggal)
        getData(); // method getData() sudah mengambil semua data untuk user yang login

        // 4️⃣ Update label total data
        lbl_total.setText("TOTAL DATA: " + jTable1.getRowCount() + " Aspirasi");

        // 5️⃣ Pesan opsional
        // JOptionPane.showMessageDialog(this, "Data berhasil direfresh!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal refresh: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmb_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kategoriActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
 // Membuat model tabel baru (wadah untuk menampung data hasil query)
        DefaultTableModel model = new DefaultTableModel();

        // Menambahkan nama kolom pada tabel
        model.addColumn("No");                // Nomor urut
        model.addColumn("ID Pengaduan");      // ID pengaduan
        model.addColumn("NIK");               // NIK pelapor
        model.addColumn("Nama");              // Nama pelapor
        model.addColumn("Tanggal");           // Tanggal pengaduan
        model.addColumn("Isi Laporan");       // Isi laporan
        model.addColumn("Foto");              // Foto bukti
        model.addColumn("Kategori");          // Kategori (Sarana/Prasarana)
        model.addColumn("Lokasi");            // Lokasi kejadian
        model.addColumn("Status");            // Status pengaduan

        try {

            // Mengambil teks dari field pencarian dan menghapus spasi berlebih
            String cari = txt_cari.getText().trim();

            // Mengambil pilihan kategori dari combobox
            String kategori = cmb_kategori.getSelectedItem().toString();

            // Query dasar (1=1 supaya mudah ditambahkan kondisi AND)
            String sql = "SELECT * FROM pengaduan WHERE 1=1";

            // Jika kolom pencarian tidak kosong, tambahkan filter nama
            if (!cari.equals("")) {
                sql += " AND nama LIKE ?";
            }

            // Jika kategori bukan "Semua", tambahkan filter kategori
            if (!kategori.equals("Semua")) {
                sql += " AND Kategori = ?";
            }

            // Mengurutkan data berdasarkan tanggal terbaru
            sql += " ORDER BY tgl_pengaduan DESC";

            // Menyiapkan prepared statement
            PreparedStatement pst = conn.prepareStatement(sql);

            int index = 1; // Untuk mengatur urutan tanda ? pada query

            // Jika ada pencarian nama, isi parameter pertama
            if (!cari.equals("")) {
                pst.setString(index++, "%" + cari + "%"); 
                // % digunakan agar bisa mencari sebagian kata
            }

            // Jika ada filter kategori, isi parameter berikutnya
            if (!kategori.equals("Semua")) {
                pst.setString(index++, kategori);
            }

            // Menjalankan query
            ResultSet res = pst.executeQuery();

            int no = 1; // Nomor urut tabel

            // Perulangan untuk mengambil semua data dari hasil query
            while (res.next()) {

                // Menambahkan setiap baris data ke dalam tabel
                model.addRow(new Object[]{
                    no++,                                   // Nomor urut otomatis
                    res.getString("id_pengaduan"),           // Ambil data id_pengaduan
                    res.getString("nik"),                    // Ambil data nik
                    res.getString("nama"),                   // Ambil data nama
                    res.getString("tgl_pengaduan"),          // Ambil tanggal
                    res.getString("isi_laporan"),            // Ambil isi laporan
                    res.getString("foto"),                   // Ambil foto
                    res.getString("Kategori"),               // Ambil kategori
                    res.getString("lokasi"),                 // Ambil lokasi
                    res.getString("status")                  // Ambil status
                });
            }

            // Menampilkan model ke JTable
            jTable1.setModel(model);

            // Menampilkan total data yang ditemukan
            lbl_total.setText("TOTAL HASIL: " + model.getRowCount() + " Data");

        } catch (Exception e) {

            // Menampilkan error di console (agar tidak mengganggu auto-search)
            System.out.println("Error search: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datapengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datapengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datapengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datapengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datapengaduan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_kategori;
    private javax.swing.JButton filtter;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
    
}
