/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riwayat;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import ukk.session;


/**
 *
 * @author ASUS
 */
public class RiwayatAspirasi extends javax.swing.JFrame {

    /**
     * Creates new form RiwayatAspirasi
     */
   
    PreparedStatement pst = null;
   
    public RiwayatAspirasi() {
        initComponents();
        load_riwayat();
        this.setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    
    }
    
    public void load_riwayat() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Tanggal");
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi");
    model.addColumn("Kategori");
    model.addColumn("Status");

   try {
    int no = 1;

    Connection conn = Koneksi.Koneksi.KoneksiDB();
    PreparedStatement pst;
    ResultSet res;

    // 🔥 Tanpa session → selalu tampil semua
    String sql = "SELECT * FROM aspirasi ORDER BY tanggal DESC";
    pst = conn.prepareStatement(sql);

    res = pst.executeQuery();

    while (res.next()) {
        model.addRow(new Object[]{
            no++,
            res.getString("tanggal"),
            res.getString("nama"),
            res.getString("isi_aspirasi"),
            res.getString("kategori"),
            res.getString("status")
        });
    }

    tb_riwayat.setModel(model);
    lbl_total.setText("TOTAL DATA: " + tb_riwayat.getRowCount() + " Aspirasi");

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal Load Data: " + e.getMessage());
}
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_riwayat = new javax.swing.JTable();
        txt_cari_nama = new javax.swing.JTextField();
        cb_kategori = new javax.swing.JComboBox<>();
        tgl_dari = new com.toedter.calendar.JDateChooser();
        tgl_sampai = new com.toedter.calendar.JDateChooser();
        btn_filter = new javax.swing.JButton();
        lbl_total = new javax.swing.JLabel();
        btn_detail = new javax.swing.JButton();
        btn_cetak_filter = new javax.swing.JButton();
        btn_cetak_all = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "Nama ", "Isi Aspirasi", "Kategori", "Status"
            }
        ));
        jScrollPane1.setViewportView(tb_riwayat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 1620, 570));

        txt_cari_nama.setBackground(new java.awt.Color(0,0,0,0));
        txt_cari_nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cari_nama.setBorder(null);
        txt_cari_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_namaActionPerformed(evt);
            }
        });
        txt_cari_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cari_namaKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cari_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 740, 50));

        cb_kategori.setBackground(new java.awt.Color(0,0,0,0));
        cb_kategori.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama", "Kategori" }));
        cb_kategori.setBorder(null);
        jPanel1.add(cb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 180, 210, 50));

        tgl_dari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tgl_dari, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 280, 30));

        tgl_sampai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tgl_sampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 250, 30));

        btn_filter.setBackground(new java.awt.Color(0,0,0,0));
        btn_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 240, 150, 50));

        lbl_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_total.setText("TOTAL DATA :");
        jPanel1.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 960, -1, -1));

        btn_detail.setBackground(new java.awt.Color(0,0,0,0));
        btn_detail.setBorder(null);
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });
        jPanel1.add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 950, 120, 40));

        btn_cetak_filter.setBackground(new java.awt.Color(0,0,0,0));
        btn_cetak_filter.setBorder(null);
        btn_cetak_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak_filterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetak_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 950, 120, 40));

        btn_cetak_all.setBackground(new java.awt.Color(0,0,0,0));
        btn_cetak_all.setBorder(null);
        btn_cetak_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak_allActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetak_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 950, 110, 40));

        jButton1.setBackground(new java.awt.Color(0,0,0,0));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 950, 110, 40));

        jButton2.setBackground(new java.awt.Color(0,0,0,0));
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 950, 120, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/riwayat aspirasi adm.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -2, 1930, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filterActionPerformed
        // TODO add your handling code here :                                                                                  
    if (tgl_dari.getDate() == null || tgl_sampai.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Silakan pilih rentang tanggal!");
        return;
    }

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Tanggal");
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi");
    model.addColumn("Kategori"); // Tambahkan ini
    model.addColumn("Status");

    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dari = sdf.format(tgl_dari.getDate());
        String sampai = sdf.format(tgl_sampai.getDate());

        int no = 1;
        String sql = "SELECT * FROM aspirasi WHERE tanggal BETWEEN ? AND ? ORDER BY tanggal ASC";
        
        java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, dari);
        pst.setString(2, sampai);
        java.sql.ResultSet res = pst.executeQuery();

        while (res.next()) {
            model.addRow(new Object[]{
                no++, 
                res.getString("tanggal"), 
                res.getString("nama"), 
                res.getString("isi_aspirasi"), 
                res.getString("kategori"), // Tambahkan ini
                res.getString("status")
            });
        }
        tb_riwayat.setModel(model);
        lbl_total.setText("TOTAL DATA FILTER: " + tb_riwayat.getRowCount() + " Aspirasi");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal filter: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_filterActionPerformed

    private void btn_cetak_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak_filterActionPerformed
        // TODO add your handling code here:                                                                                               
   try {

    if (tgl_dari.getDate() == null || tgl_sampai.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Silakan pilih rentang tanggal!");
        return;
    }

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String dari = sdf.format(tgl_dari.getDate());
    String sampai = sdf.format(tgl_sampai.getDate());

    String sql = "SELECT "
        + "id_aspirasi AS aspirasi_id_aspirasi, "
        + "nik AS aspirasi_nik, "
        + "nama AS aspirasi_nama, "
        + "isi_aspirasi AS aspirasi_isi_aspirasi, "
        + "kategori AS aspirasi_kategori, "
        + "status AS aspirasi_status, "
        + "tanggal AS aspirasi_tanggal, "
        + "tanggal_tang AS aspirasi_tanggal_tang "
        + "FROM aspirasi "
        + "WHERE tanggal BETWEEN ? AND ? "
        + "AND status IN ('terimakasih','diterapkan') "
        + "ORDER BY tanggal ASC";

    Connection conn = Koneksi.Koneksi.KoneksiDB();
    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, dari);
    pst.setString(2, sampai);

    ResultSet rp = pst.executeQuery();

    JRResultSetDataSource jrRS = new JRResultSetDataSource(rp);

    JasperReport jasperReport = JasperCompileManager.compileReport(
            "D:/buiza/ukk/src/report/aspirasi.jrxml"
    );

    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);

    JRViewer viewer = new JRViewer(jasperPrint);
    JDialog dialog = new JDialog();
    dialog.setTitle("Laporan Data Aspirasi");
    dialog.setAlwaysOnTop(true);
    dialog.getContentPane().add(viewer);

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    dialog.setBounds(0, 0, screenSize.width, screenSize.height);
    dialog.setVisible(true);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal Cetak Laporan: " + e.getMessage());
    e.printStackTrace();
}
    }//GEN-LAST:event_btn_cetak_filterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
    txt_cari_nama.setText("");        // Mengosongkan kolom cari
    tgl_dari.setDate(null);           // Mengosongkan filter tanggal awal
    tgl_sampai.setDate(null);         // Mengosongkan filter tanggal akhir
    cb_kategori.setSelectedIndex(0);  // Mengembalikan combobox ke pilihan pertama
    load_riwayat();                   // Memanggil kembali semua data dari database

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        // TODO add your handling code here:                                                                                                                              
    int baris = tb_riwayat.getSelectedRow(); 
    
    if (baris != -1) {
        try {
            // Index: 0=No, 1=Tanggal, 2=Nama, 3=Isi, 4=Kategori, 5=Status
            String tgl    = tb_riwayat.getValueAt(baris, 1).toString();
            String nama   = tb_riwayat.getValueAt(baris, 2).toString();
            String isi    = tb_riwayat.getValueAt(baris, 3).toString();
            String ktgri  = tb_riwayat.getValueAt(baris, 4).toString();
            String status = tb_riwayat.getValueAt(baris, 5).toString();

            String detail = "DETAIL ASPIRASI (MODE ADMIN)\n"
                          + "--------------------------------------\n"
                          + "Tanggal      : " + tgl + "\n"
                          + "Nama         : " + nama + "\n"
                          + "Kategori     : " + ktgri + "\n"
                          + "Status Saat Ini : " + status + "\n"
                          + "--------------------------------------\n"
                          + "Isi Aspirasi :\n" + isi + "\n"
                          + "--------------------------------------";

            JOptionPane.showMessageDialog(this, detail, "Detail Data", JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil detail: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih baris tabel terlebih dahulu!");
    }

    }//GEN-LAST:event_btn_detailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:                                        
    // 1. Memanggil objek Menu Admin
    // Sesuaikan nama class dengan file menu utama Anda (berdasarkan gambar: menuAdmin)
    ukk.menu.menuAdmin menu = new ukk.menu.menuAdmin();
    
    // 2. Menampilkan Menu Admin
    menu.setVisible(true);
    
    // 3. Menutup halaman Riwayat Aspirasi saat ini
    this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_cetak_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak_allActionPerformed
//           // TODO add your handling code here:                                            
//     // 1. Pastikan koneksi tidak null
//        Connection conn = Koneksi.Koneksi.KoneksiDB(); 
//        if (conn == null) {
//            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal!");
//            return;
//        }
        String sql = "SELECT " +
             "aspirasi.id_aspirasi AS aspirasi_id_aspirasi, " +
             "aspirasi.nik AS aspirasi_nik, " +
             "aspirasi.nama AS aspirasi_nama, " +
             "aspirasi.isi_aspirasi AS aspirasi_isi_aspirasi, " +
             "aspirasi.kategori AS aspirasi_kategori, " +
             "aspirasi.status AS aspirasi_status, " +
             "aspirasi.tanggal AS aspirasi_tanggal, " +
             "aspirasi.tanggal_tang AS aspirasi_tanggal_tang " +
             "FROM aspirasi aspirasi";

try {

    Connection conn = Koneksi.Koneksi.KoneksiDB();
    PreparedStatement pst = conn.prepareStatement(sql);
    ResultSet rp = pst.executeQuery();

    JRResultSetDataSource jrRS = new JRResultSetDataSource(rp);

    JasperReport jasperReport = JasperCompileManager.compileReport(
            "D:/buiza/ukk/src/report/aspirasi.jrxml"
    );

    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);

    JRViewer viewer = new JRViewer(jasperPrint);
    JDialog dialog = new JDialog();
    dialog.setTitle("Laporan Data Aspirasi");
    dialog.setAlwaysOnTop(true);
    dialog.getContentPane().add(viewer);

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    dialog.setBounds(0, 0, screenSize.width, screenSize.height);
    dialog.setVisible(true);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal Cetak Laporan: " + e.getMessage());
    e.printStackTrace();
}

    
    }//GEN-LAST:event_btn_cetak_allActionPerformed

    private void txt_cari_namaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_namaKeyReleased
        // TODO add your handling code here:                                        
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Tanggal");
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi");
    model.addColumn("Kategori"); 
    model.addColumn("Status");

    try {
        String cari = txt_cari_nama.getText();
        // Query tetap sama, mencari dari depan
        String sql = "SELECT * FROM aspirasi WHERE (nama LIKE ? OR kategori LIKE ? OR isi_aspirasi LIKE ?) ORDER BY tanggal DESC";

        java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, cari + "%"); 
        pst.setString(2, cari + "%"); 
        pst.setString(3, cari + "%"); 
        
        java.sql.ResultSet res = pst.executeQuery();

        int no = 1;
        while (res.next()) {
            model.addRow(new Object[]{
                no++, 
                res.getString("tanggal"), 
                res.getString("nama"), 
                res.getString("isi_aspirasi"), 
                res.getString("kategori"), 
                res.getString("status")
            });
        }
        tb_riwayat.setModel(model);
        lbl_total.setText("TOTAL HASIL: " + tb_riwayat.getRowCount() + " Aspirasi");

    } catch (Exception e) {
        // Untuk auto-search, sebaiknya tidak pakai JOptionPane error agar tidak mengganggu saat mengetik
        System.out.println("Error search: " + e.getMessage());
    }

    }//GEN-LAST:event_txt_cari_namaKeyReleased

    private void txt_cari_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cari_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatAspirasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatAspirasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatAspirasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatAspirasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatAspirasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak_all;
    private javax.swing.JButton btn_cetak_filter;
    private javax.swing.JButton btn_detail;
    private javax.swing.JButton btn_filter;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tb_riwayat;
    private com.toedter.calendar.JDateChooser tgl_dari;
    private com.toedter.calendar.JDateChooser tgl_sampai;
    private javax.swing.JTextField txt_cari_nama;
    // End of variables declaration//GEN-END:variables
}
