/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riwayat;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ukk.menu.menuAdmin;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import Koneksi.Koneksi;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

public class RiwayatTanggapanAdmin extends javax.swing.JFrame {
    private final DefaultTableModel model;

    public RiwayatTanggapanAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        model = new DefaultTableModel();
        model.addColumn("ID Tanggapan");
        model.addColumn("ID Peng");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Tanggal Pengaduan");
        model.addColumn("Tanggal Tanggapan");
        model.addColumn("Nama Petugas");
        model.addColumn("Isi Pengaduan");
        model.addColumn("Kategori");
        model.addColumn("Lokasi");
        model.addColumn("Status");
        model.addColumn("Feedback");
        model.addColumn("Foto");

        tabel_pengaduan.setModel(model);

        tampilData(); 

        }
    
//    private void tampilkanFoto(String path) {
//    try {
//        ImageIcon icon = new ImageIcon(path);
//        Image img = icon.getImage().getScaledInstance(
//                lblFoto.getWidth(),
//                lblFoto.getHeight(),
//                Image.SCALE_SMOOTH);
//
//        lblFoto.setIcon(new ImageIcon(img));
//    } catch (Exception e) {
//        lblFoto.setText("Foto tidak ditemukan");
//    }
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pengaduan = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 270, 40));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 260, 40));

        tabel_pengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pengaduan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pengaduanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pengaduan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 1290, 480));

        jButton3.setBackground(new java.awt.Color(0,0,0,0));
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 160, 50));

        jButton4.setBackground(new java.awt.Color(0,0,0,0));
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 190, 50));

        jButton5.setBackground(new java.awt.Color(0,0,0,0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 630, 210, 50));

        jButton6.setBackground(new java.awt.Color(0,0,0,0));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 640, 140, 50));

        jButton7.setBackground(new java.awt.Color(0,0,0,0));
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 630, 100, 60));

        jButton2.setBackground(new java.awt.Color(0,0,0,0));
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 90, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/riwayat/riwayat tanggapan.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    int baris = tabel_pengaduan.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu!");
        return;
    }

    // Ambil data dari tabel
    String idTanggapan = model.getValueAt(baris, 0).toString();
    String idPengaduan = model.getValueAt(baris, 1).toString();
    String nik = model.getValueAt(baris, 2).toString();
    String nama = model.getValueAt(baris, 3).toString();
    String tglPengaduan = model.getValueAt(baris, 4).toString();
    String tglTanggapan = model.getValueAt(baris, 5).toString();
    String petugas = model.getValueAt(baris, 6).toString();
    String isi = model.getValueAt(baris, 7).toString();
    String kategori = model.getValueAt(baris, 8).toString();
    String lokasi = model.getValueAt(baris, 9).toString();
    String status = model.getValueAt(baris, 10).toString();
    String feedback = model.getValueAt(baris, 11).toString();
    String foto = model.getValueAt(baris, 12).toString();

    // 🔥 Load & resize gambar
    ImageIcon icon = new ImageIcon(foto);
    Image img = icon.getImage().getScaledInstance(180, 220, Image.SCALE_SMOOTH);
    ImageIcon resizeIcon = new ImageIcon(img);
    JLabel lblGambar = new JLabel(resizeIcon);

    // 🔥 Text detail
    JTextArea textArea = new JTextArea(
            "ID Tanggapan : " + idTanggapan +
            "\nID Pengaduan : " + idPengaduan +
            "\nNIK : " + nik +
            "\nNama : " + nama +
            "\nTanggal Pengaduan : " + tglPengaduan +
            "\nTanggal Tanggapan : " + tglTanggapan +
            "\nPetugas : " + petugas +
            "\nIsi : " + isi +
            "\nKategori : " + kategori +
            "\nLokasi : " + lokasi +
            "\nStatus : " + status +
            "\nFeedback : " + feedback
    );

    textArea.setEditable(false);
    textArea.setOpaque(false);

    // 🔥 Panel gabungan
    JPanel panel = new JPanel(new BorderLayout());
    panel.add(textArea, BorderLayout.CENTER);
    panel.add(lblGambar, BorderLayout.EAST);

    JOptionPane.showMessageDialog(null, panel, "Detail Data", JOptionPane.PLAIN_MESSAGE);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
  
    jDateChooser1.setDate(null);
    jDateChooser2.setDate(null);
    tampilData(); // Memanggil fungsi tampil data awal

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                                        
    // 1. Tampilkan dialog konfirmasi
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin kembali ke Menu Utama?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);

    // 2. Jika user pilih 'Yes' (Ya)
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // Panggil Menu Admin (Pastikan nama class-nya benar)
            // Jika MenuAdmin ada di package lain, NetBeans akan minta Import otomatis
            new ukk.menu.menuAdmin().setVisible(true); 
            
            // Tutup form riwayat yang sekarang
            this.dispose(); 
        } catch (Exception e) {
            // Jaga-jaga kalau ada error saat pindah form
            JOptionPane.showMessageDialog(this, "Gagal kembali ke menu: " + e.getMessage());
        }
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tabel_pengaduanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pengaduanMouseClicked
//                                            
//    int baris = tabel_pengaduan.getSelectedRow();
//    if (baris == -1) return;
//
//    try {
//        // 1. Mengambil data FOTO dari kolom ke-7 (Sesuaikan urutan kolom database kamu)
//        Object dataFoto = tabel_pengaduan.getValueAt(baris, 7);
//        String foto = (dataFoto != null) ? dataFoto.toString() : "";
//
//        if (!foto.equals("")) {
//            // 2. Tentukan lokasi file (Pastikan folder foto sudah benar)
//            File file = new File("src/img_laporan/" + foto); 
//            
//            if (file.exists()) {
//                ImageIcon icon = new ImageIcon(file.getAbsolutePath());
//                // 3. Mengatur ukuran gambar agar pas dengan kotak jLabel8 (Preview)
//                Image img = icon.getImage().getScaledInstance(
//                        jLabel8.getWidth(), 
//                        jLabel8.getHeight(), 
//                        Image.SCALE_SMOOTH);
//                jLabel8.setIcon(new ImageIcon(img));
//                jLabel8.setText(""); // Menghapus teks jika gambar ditemukan
//            } else {
//                jLabel8.setIcon(null); 
//                jLabel8.setText("File Tidak Ditemukan");
//            }
//        } else {
//            jLabel8.setIcon(null);
//            jLabel8.setText("Tidak Ada Foto");
//        }
//    } catch (Exception e) {
//        System.out.println("Error preview foto: " + e.getMessage());
//        jLabel8.setText("Error Load");
//    }

        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_pengaduanMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String sql = "SELECT " +
        "pengaduan.id_pengaduan AS pengaduan_id_pengaduan, " +
        "pengaduan.nik AS pengaduan_nik, " +
        "pengaduan.tgl_pengaduan AS pengaduan_tgl_pengaduan, " +
        "pengaduan.isi_laporan AS pengaduan_isi_laporan, " +
        "pengaduan.nama AS pengaduan_nama, " +
        "pengaduan.foto AS pengaduan_foto, " +
        "pengaduan.lokasi AS pengaduan_lokasi, " +
        "pengaduan.Kategori AS pengaduan_Kategori, " +
        "pengaduan.status AS pengaduan_status, " +
        "tanggapan.id_tanggapan AS tanggapan_id_tanggapan, " +
        "tanggapan.nik AS tanggapan_nik, " +
        "tanggapan.nama AS tanggapan_nama, " +
        "tanggapan.isi_pengaduan AS tanggapan_isi_pengaduan, " +
        "tanggapan.feedback AS tanggapan_feedback, " +
        "tanggapan.status AS tanggapan_status, " +
        "tanggapan.tanggal AS tanggapan_tanggal, " +
        "tanggapan.foto AS tanggapan_foto, " +
        "tanggapan.id_pengaduan AS tanggapan_id_pengaduan, " +
        "tanggapan.tgl_tang AS tanggapan_tgl_tang, " +
        "tanggapan.kategori AS tanggapan_kategori, " +
        "tanggapan.lokasi AS tanggapan_lokasi, " +
        "tanggapan.id_petugas AS tanggapan_id_petugas " +
        "FROM pengaduan " +
        "INNER JOIN tanggapan ON pengaduan.id_pengaduan = tanggapan.id_pengaduan " +
        "WHERE LOWER(pengaduan.status) = 'tertanggapi' " +
        "ORDER BY pengaduan.tgl_pengaduan DESC";

try {

    Connection conn = Koneksi.KoneksiDB();
    PreparedStatement pst = conn.prepareStatement(sql);
    ResultSet rp = pst.executeQuery();

    JRResultSetDataSource jrRS = new JRResultSetDataSource(rp);

    JasperReport jasperReport = JasperCompileManager.compileReport(
            "C:/Users/10/ukk-baruu/src/report/LAPENGALL.jrxml"
    );

    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);

    JRViewer viewer = new JRViewer(jasperPrint);
    JDialog dialog = new JDialog();
    dialog.setTitle("Laporan Data Pengaduan & Tanggapan");
    dialog.setAlwaysOnTop(true);
    dialog.getContentPane().add(viewer);

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    dialog.setBounds(0, 0, screenSize.width, screenSize.height);
    dialog.setVisible(true);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal Cetak Laporan: " + e.getMessage());
    e.printStackTrace();
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try {
        if (jDateChooser1.getDate() == null || jDateChooser2.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Pilih tanggal terlebih dahulu!");
            return;
        }

        // Kosongkan tabel dulu
        DefaultTableModel model = (DefaultTableModel) tabel_pengaduan.getModel();
        model.setRowCount(0);

        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String dari = df.format(jDateChooser1.getDate());
        String sampai = df.format(jDateChooser2.getDate());

        Connection conn = Koneksi.KoneksiDB();

        String sql = "SELECT tanggapan.*, pengaduan.tgl_pengaduan " +
                     "FROM tanggapan " +
                     "INNER JOIN pengaduan ON tanggapan.id_pengaduan = pengaduan.id_pengaduan " +
                     "WHERE LOWER(tanggapan.status) = 'tertanggapi' " +
                     "AND DATE(tanggapan.tgl_tang) BETWEEN ? AND ? " +
                     "ORDER BY tanggapan.tgl_tang DESC";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, dari);
        pst.setString(2, sampai);

        ResultSet rs = pst.executeQuery();

        boolean dataAda = false;

        while (rs.next()) {
            dataAda = true;

            Object[] row = {
                rs.getString("id_tanggapan"),
                rs.getString("id_pengaduan"),
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("tanggal"),      // Tanggal Pengaduan
                rs.getString("tgl_tang"),     // Tanggal Tanggapan
                rs.getString("id_petugas"),   // Kalau belum ada nama petugas
                rs.getString("isi_pengaduan"),
                rs.getString("kategori"),
                rs.getString("lokasi"),
                rs.getString("status"),
                rs.getString("feedback"),
                rs.getString("foto")
            };

            model.addRow(row);
        }

        if (!dataAda) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Filter: " + e.getMessage());
        e.printStackTrace();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                                            
    try {

        // 1️⃣ Cek tanggal
        if (jDateChooser1.getDate() == null || jDateChooser2.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Pilih tanggal terlebih dahulu!");
            return;
        }

        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String dari = df.format(jDateChooser1.getDate());
        String sampai = df.format(jDateChooser2.getDate());

        Connection conn = Koneksi.KoneksiDB();

        // 2️⃣ QUERY FINAL
        String sql = "SELECT " +
             "p.id_pengaduan AS pengaduan_id_pengaduan, " +
             "p.nik AS pengaduan_nik, " +
             "p.tgl_pengaduan AS pengaduan_tgl_pengaduan, " +
             "p.isi_laporan AS pengaduan_isi_laporan, " +
             "p.nama AS pengaduan_nama, " +
             "p.foto AS pengaduan_foto, " +
             "p.lokasi AS pengaduan_lokasi, " +
             "p.Kategori AS pengaduan_Kategori, " +
             "p.status AS pengaduan_status, " +

             "t.id_tanggapan AS tanggapan_id_tanggapan, " +
             " t.id_pengaduan AS tanggapan_id_pengaduan," +
             "t.nik AS tanggapan_nik, " +
             "t.nama AS tanggapan_nama, " +
             "t.isi_pengaduan AS tanggapan_isi_pengaduan, " +
             "t.feedback AS tanggapan_feedback, " +
             "t.status AS tanggapan_status, " +
             "t.tgl_tang AS tanggapan_tanggal, " +
             "t.tgl_tang AS tanggapan_tgl_tang, " +   // 🔥 INI YANG PENTING
             "t.foto AS tanggapan_foto, " +
             "t.kategori AS tanggapan_kategori, " +
             "t.lokasi AS tanggapan_lokasi, " +
             "t.id_petugas AS tanggapan_id_petugas " +

             "FROM tanggapan t " +
             "INNER JOIN pengaduan p ON t.id_pengaduan = p.id_pengaduan " +
             "WHERE t.status = 'tertanggapi' " +
             "AND DATE(t.tgl_tang) BETWEEN ? AND ? " +
             "ORDER BY t.tgl_tang DESC";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, dari);
        pst.setString(2, sampai);

        ResultSet rs = pst.executeQuery();

        if (!rs.isBeforeFirst()) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
            return;
        }

        JRResultSetDataSource dataSource = new JRResultSetDataSource(rs);

        // 3️⃣ LOAD & COMPILE JRXML (ANTI NULL ERROR)
        InputStream reportStream = getClass()
                .getClassLoader()
                .getResourceAsStream("report/LAPENGALL.jrxml");

        if (reportStream == null) {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan!");
            return;
        }

        JasperReport jr = JasperCompileManager.compileReport(reportStream);

        JasperPrint jp = JasperFillManager.fillReport(jr, null, dataSource);

        JasperViewer viewer = new JasperViewer(jp, false);
        viewer.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // fullscreen
        viewer.setFitPageZoomRatio(); // pas dengan halaman
        viewer.setVisible(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Cetak Laporan: " + e.getMessage());
        e.printStackTrace();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatTanggapanAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_pengaduan;
    // End of variables declaration//GEN-END:variables

   

private void tampilData() {
    model.setRowCount(0);

    try {
        Connection conn = Koneksi.KoneksiDB();
        String sql = "SELECT * FROM tanggapan "
           + "WHERE status = 'tertanggapi' "
           + "ORDER BY id_tanggapan ASC";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            String[] data = {
                rs.getString("id_tanggapan"),
                rs.getString("id_pengaduan"),
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("tanggal"),      // Tanggal Pengaduan
                rs.getString("tgl_tang"),     // Tanggal Tanggapan
                rs.getString("id_petugas"),   // Kalau belum ada nama petugas
                rs.getString("isi_pengaduan"),
                rs.getString("kategori"),
                rs.getString("lokasi"),
                rs.getString("status"),
                rs.getString("feedback"),
                rs.getString("foto")
            };

            model.addRow(data);
        }

        rs.close();
        st.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal tampil data: " + e.getMessage());
    }
}


private void cariData() {
    model.setRowCount(0);
    try {
        java.text.SimpleDateFormat df = new java.text.SimpleDateFormat("yyyy-MM-dd");
        
        // Ambil nilai tanggal
        String tglDari = df.format(jDateChooser1.getDate());
        String tglSampai = df.format(jDateChooser2.getDate());

        Connection conn = Koneksi.KoneksiDB();
        String sql = "SELECT * FROM tanggapan "
           + "WHERE DATE(tgl_pengaduan) BETWEEN ? AND ? "
           + "AND status = 'tertanggapi'";
        
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, tglDari);
        pst.setString(2, tglSampai);
        ResultSet rs = pst.executeQuery();
        
        boolean dataDitemukan = false;
        while (rs.next()) {
            dataDitemukan = true;
            Object[] obj = {
                rs.getString("id_tanggapan"),
                rs.getString("id_pengaduan"),
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("tanggal"),      // Tanggal Pengaduan
                rs.getString("tgl_tang"),     // Tanggal Tanggapan
                rs.getString("id_petugas"),   // Kalau belum ada nama petugas
                rs.getString("isi_pengaduan"),
                rs.getString("kategori"),
                rs.getString("lokasi"),
                rs.getString("status"),
                rs.getString("feedback"),
                rs.getString("foto")
            };
            model.addRow(obj);
        }
        
        if (!dataDitemukan) {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan pada rentang tanggal tersebut.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Filter: " + e.getMessage());
        e.printStackTrace(); // Agar error muncul di panel output NetBeans
    }
}
}