/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riwayat;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ukk.menu.menuAdmin;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import Koneksi.Koneksi;

public class RiwayatTanggapanAdmin extends javax.swing.JFrame {
    private final DefaultTableModel model;

    public RiwayatTanggapanAdmin() {
        initComponents();
    String[] judul = {"ID", "NIK", "Nama", "Tanggal", "Kategori", "Isi Laporan", "Status", "Feedback", "Foto"};
    model = new DefaultTableModel(judul, 0);
    tabel_pengaduan.setModel(model); 
    tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pengaduan = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("RIWAYAT PENGADUAN");

        tabel_pengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pengaduan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pengaduanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pengaduan);

        jButton3.setText("Detail");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cetak Filter");

        jButton5.setText("Cetak Semua");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setText("Filter Tanggal");

        jLabel3.setText("Sampai");

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setText("Priview Data");

        jButton2.setText("cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1111, 1111, 1111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jLabel4)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton7))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                          
   tabel_pengaduanMouseClicked(null); 
        JOptionPane.showMessageDialog(this, "Detail foto dimuat di preview.");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                                            
  
    jDateChooser1.setDate(null);
    jDateChooser2.setDate(null);
    tampilData(); // Memanggil fungsi tampil data awal

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                                        
    // 1. Tampilkan dialog konfirmasi
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin kembali ke Menu Utama?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);

    // 2. Jika user pilih 'Yes' (Ya)
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // Panggil Menu Admin (Pastikan nama class-nya benar)
            // Jika MenuAdmin ada di package lain, NetBeans akan minta Import otomatis
            new ukk.menu.menuAdmin().setVisible(true); 
            
            // Tutup form riwayat yang sekarang
            this.dispose(); 
        } catch (Exception e) {
            // Jaga-jaga kalau ada error saat pindah form
            JOptionPane.showMessageDialog(this, "Gagal kembali ke menu: " + e.getMessage());
        }
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tabel_pengaduanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pengaduanMouseClicked
                                            
    int baris = tabel_pengaduan.getSelectedRow();
    if (baris == -1) return;

    try {
        // 1. Mengambil data FOTO dari kolom ke-7 (Sesuaikan urutan kolom database kamu)
        Object dataFoto = tabel_pengaduan.getValueAt(baris, 7);
        String foto = (dataFoto != null) ? dataFoto.toString() : "";

        if (!foto.equals("")) {
            // 2. Tentukan lokasi file (Pastikan folder foto sudah benar)
            File file = new File("src/img_laporan/" + foto); 
            
            if (file.exists()) {
                ImageIcon icon = new ImageIcon(file.getAbsolutePath());
                // 3. Mengatur ukuran gambar agar pas dengan kotak jLabel8 (Preview)
                Image img = icon.getImage().getScaledInstance(
                        jLabel8.getWidth(), 
                        jLabel8.getHeight(), 
                        Image.SCALE_SMOOTH);
                jLabel8.setIcon(new ImageIcon(img));
                jLabel8.setText(""); // Menghapus teks jika gambar ditemukan
            } else {
                jLabel8.setIcon(null); 
                jLabel8.setText("File Tidak Ditemukan");
            }
        } else {
            jLabel8.setIcon(null);
            jLabel8.setText("Tidak Ada Foto");
        }
    } catch (Exception e) {
        System.out.println("Error preview foto: " + e.getMessage());
        jLabel8.setText("Error Load");
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_pengaduanMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                                                                                         
   

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                        
    System.out.println("Tombol diklik!"); // Ini untuk ngetes di panel Output bawah
    
    if (jDateChooser1.getDate() == null || jDateChooser2.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Harap pilih kedua tanggal filter!");
    } else {
        cariData(); 
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatTanggapanAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_pengaduan;
    // End of variables declaration//GEN-END:variables

   

private void tampilData() {
    model.setRowCount(0);
    try {
        Connection conn = Koneksi.KoneksiDB(); 
        // Menggunakan LEFT JOIN agar feedback admin terbawa
        String sql = "SELECT p.*, t.feedback FROM pengaduan p " +
                     "LEFT JOIN tanggapan t ON p.id_pengaduan = t.id_pengaduan";
        ResultSet rs = conn.createStatement().executeQuery(sql);
        
        while (rs.next()) {
            String fb = rs.getString("feedback");
            String[] data = {
                rs.getString("id_pengaduan"),
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("tgl_pengaduan"),
                rs.getString("kategori"),
                rs.getString("isi_laporan"),
                rs.getString("status"),
                // Jika feedback admin kosong, tampilkan pesan default
                (fb == null || fb.isEmpty()) ? "Belum ditanggapi" : fb, 
                rs.getString("foto") 
            };
            model.addRow(data);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal tampil data: " + e.getMessage());
    }
}

private void cariData() {
    model.setRowCount(0);
    try {
        java.text.SimpleDateFormat df = new java.text.SimpleDateFormat("yyyy-MM-dd");
        
        // Ambil nilai tanggal
        String tglDari = df.format(jDateChooser1.getDate());
        String tglSampai = df.format(jDateChooser2.getDate());

        Connection conn = Koneksi.KoneksiDB();
        String sql = "SELECT * FROM pengaduan WHERE DATE(tgl_pengaduan) BETWEEN ? AND ?";
        
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, tglDari);
        pst.setString(2, tglSampai);
        ResultSet rs = pst.executeQuery();
        
        boolean dataDitemukan = false;
        while (rs.next()) {
            dataDitemukan = true;
            Object[] obj = {
                rs.getString("id_pengaduan"),
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("tgl_pengaduan"),
                rs.getString("kategori"),
                rs.getString("isi_laporan"),
                rs.getString("status"),
                rs.getString("foto")
            };
            model.addRow(obj);
        }
        
        if (!dataDitemukan) {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan pada rentang tanggal tersebut.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Filter: " + e.getMessage());
        e.printStackTrace(); // Agar error muncul di panel output NetBeans
    }
}
}