/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riwayat_p;

import riwayat.*;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ukk.menu.menuAdmin;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import Koneksi.Koneksi;
import java.awt.BorderLayout;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import ukk.session;

public class RiwayatTanggapanP extends javax.swing.JFrame {
    private final DefaultTableModel model;

    public RiwayatTanggapanP() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        model = new DefaultTableModel();
        model.addColumn("ID Tanggapan");
        model.addColumn("ID Peng");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Tanggal Pengaduan");
        model.addColumn("Tanggal Tanggapan");
        model.addColumn("Nama Petugas");
        model.addColumn("Isi Pengaduan");
        model.addColumn("Kategori");
        model.addColumn("Lokasi");
        model.addColumn("Status");
        model.addColumn("Feedback");
        model.addColumn("Foto");

        tabel_pengaduan.setModel(model);

        tampilData(); 

        }
    
//    private void tampilkanFoto(String path) {
//    try {
//        ImageIcon icon = new ImageIcon(path);
//        Image img = icon.getImage().getScaledInstance(
//                lblFoto.getWidth(),
//                lblFoto.getHeight(),
//                Image.SCALE_SMOOTH);
//
//        lblFoto.setIcon(new ImageIcon(img));
//    } catch (Exception e) {
//        lblFoto.setText("Foto tidak ditemukan");
//    }
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pengaduan = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 280, 40));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 230, 40));

        tabel_pengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pengaduan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pengaduanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pengaduan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 1580, 570));

        jButton3.setBackground(new java.awt.Color(0,0,0,0));
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 950, 120, 40));

        jButton6.setBackground(new java.awt.Color(0,0,0,0));
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 950, 120, 40));

        jButton7.setBackground(new java.awt.Color(0,0,0,0));
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 950, 110, 40));

        jButton2.setBackground(new java.awt.Color(0,0,0,0));
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/riwayat tanggapan p.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 1, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    int baris = tabel_pengaduan.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu!");
        return;
    }

    // Ambil data dari tabel
    String idTanggapan = model.getValueAt(baris, 0).toString();
    String idPengaduan = model.getValueAt(baris, 1).toString();
    String nik = model.getValueAt(baris, 2).toString();
    String nama = model.getValueAt(baris, 3).toString();
    String tglPengaduan = model.getValueAt(baris, 4).toString();
    String tglTanggapan = model.getValueAt(baris, 5).toString();
    String petugas = model.getValueAt(baris, 6).toString();
    String isi = model.getValueAt(baris, 7).toString();
    String kategori = model.getValueAt(baris, 8).toString();
    String lokasi = model.getValueAt(baris, 9).toString();
    String status = model.getValueAt(baris, 10).toString();
    String feedback = model.getValueAt(baris, 11).toString();
    String foto = model.getValueAt(baris, 12).toString();

    // 🔥 Load & resize gambar
    ImageIcon icon = new ImageIcon(foto);
    Image img = icon.getImage().getScaledInstance(180, 220, Image.SCALE_SMOOTH);
    ImageIcon resizeIcon = new ImageIcon(img);
    JLabel lblGambar = new JLabel(resizeIcon);

    // 🔥 Text detail
    JTextArea textArea = new JTextArea(
            "ID Tanggapan : " + idTanggapan +
            "\nID Pengaduan : " + idPengaduan +
            "\nNIK : " + nik +
            "\nNama : " + nama +
            "\nTanggal Pengaduan : " + tglPengaduan +
            "\nTanggal Tanggapan : " + tglTanggapan +
            "\nPetugas : " + petugas +
            "\nIsi : " + isi +
            "\nKategori : " + kategori +
            "\nLokasi : " + lokasi +
            "\nStatus : " + status +
            "\nFeedback : " + feedback
    );

    textArea.setEditable(false);
    textArea.setOpaque(false);

    // 🔥 Panel gabungan
    JPanel panel = new JPanel(new BorderLayout());
    panel.add(textArea, BorderLayout.CENTER);
    panel.add(lblGambar, BorderLayout.EAST);

    JOptionPane.showMessageDialog(null, panel, "Detail Data", JOptionPane.PLAIN_MESSAGE);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                                            
  
    jDateChooser1.setDate(null);
    jDateChooser2.setDate(null);
    tampilData(); // Memanggil fungsi tampil data awal

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                                        
    // 1. Tampilkan dialog konfirmasi
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin kembali ke Menu Utama?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);

    // 2. Jika user pilih 'Yes' (Ya)
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // Panggil Menu Admin (Pastikan nama class-nya benar)
            // Jika MenuAdmin ada di package lain, NetBeans akan minta Import otomatis
            new ukk.menu.menuPelapor().setVisible(true); 
            
            // Tutup form riwayat yang sekarang
            this.dispose(); 
        } catch (Exception e) {
            // Jaga-jaga kalau ada error saat pindah form
            JOptionPane.showMessageDialog(this, "Gagal kembali ke menu: " + e.getMessage());
        }
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tabel_pengaduanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pengaduanMouseClicked
//                                            
//    int baris = tabel_pengaduan.getSelectedRow();
//    if (baris == -1) return;
//
//    try {
//        // 1. Mengambil data FOTO dari kolom ke-7 (Sesuaikan urutan kolom database kamu)
//        Object dataFoto = tabel_pengaduan.getValueAt(baris, 7);
//        String foto = (dataFoto != null) ? dataFoto.toString() : "";
//
//        if (!foto.equals("")) {
//            // 2. Tentukan lokasi file (Pastikan folder foto sudah benar)
//            File file = new File("src/img_laporan/" + foto); 
//            
//            if (file.exists()) {
//                ImageIcon icon = new ImageIcon(file.getAbsolutePath());
//                // 3. Mengatur ukuran gambar agar pas dengan kotak jLabel8 (Preview)
//                Image img = icon.getImage().getScaledInstance(
//                        jLabel8.getWidth(), 
//                        jLabel8.getHeight(), 
//                        Image.SCALE_SMOOTH);
//                jLabel8.setIcon(new ImageIcon(img));
//                jLabel8.setText(""); // Menghapus teks jika gambar ditemukan
//            } else {
//                jLabel8.setIcon(null); 
//                jLabel8.setText("File Tidak Ditemukan");
//            }
//        } else {
//            jLabel8.setIcon(null);
//            jLabel8.setText("Tidak Ada Foto");
//        }
//    } catch (Exception e) {
//        System.out.println("Error preview foto: " + e.getMessage());
//        jLabel8.setText("Error Load");
//    }

        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_pengaduanMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                        
    System.out.println("Tombol diklik!"); // Ini untuk ngetes di panel Output bawah
    
    if (jDateChooser1.getDate() == null || jDateChooser2.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Harap pilih kedua tanggal filter!");
    } else {
        cariData(); 
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatTanggapanP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatTanggapanP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_pengaduan;
    // End of variables declaration//GEN-END:variables

   

private void tampilData() {
    model.setRowCount(0);

    try {
        Connection conn = Koneksi.KoneksiDB();
        PreparedStatement pst;
        ResultSet rs;

        // 🔥 LOGIKA ROLE SEPERTI ASPIRASI
        if (session.getRole().equalsIgnoreCase("admin")) {

            String sql = "SELECT * FROM tanggapan ORDER BY id_tanggapan DESC";
            pst = conn.prepareStatement(sql);

        } else {

            String sql = "SELECT * FROM tanggapan WHERE nik = ? ORDER BY id_tanggapan DESC";
            pst = conn.prepareStatement(sql);
            pst.setString(1, session.getNik());
        }

        rs = pst.executeQuery();

        while (rs.next()) {
            String[] data = {
                rs.getString("id_tanggapan"),
                rs.getString("id_pengaduan"),
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("tanggal"),
                rs.getString("tgl_tang"),
                rs.getString("id_petugas"),
                rs.getString("isi_pengaduan"),
                rs.getString("kategori"),
                rs.getString("lokasi"),
                rs.getString("status"),
                rs.getString("feedback"),
                rs.getString("foto")
            };

            model.addRow(data);
        }

        rs.close();
        pst.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal tampil data: " + e.getMessage());
    }
}


private void cariData() {
    model.setRowCount(0);

    try {
        java.sql.Date sqlDari = new java.sql.Date(jDateChooser1.getDate().getTime());
        java.sql.Date sqlSampai = new java.sql.Date(jDateChooser2.getDate().getTime());

        Connection conn = Koneksi.KoneksiDB();
        PreparedStatement pst;
        ResultSet rs;

        if (session.getRole().equalsIgnoreCase("admin")) {

            String sql = "SELECT * FROM tanggapan WHERE DATE(tgl_tang) BETWEEN ? AND ?";
            pst = conn.prepareStatement(sql);
            pst.setDate(1, sqlDari);
            pst.setDate(2, sqlSampai);

        } else {

            String sql = "SELECT * FROM tanggapan WHERE nik = ? AND DATE(tgl_tang) BETWEEN ? AND ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, session.getNik());
            pst.setDate(2, sqlDari);
            pst.setDate(3, sqlSampai);
        }

        rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_tanggapan"),
                rs.getString("id_pengaduan"),
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("tanggal"),
                rs.getString("tgl_tang"),
                rs.getString("id_petugas"),
                rs.getString("isi_pengaduan"),
                rs.getString("kategori"),
                rs.getString("lokasi"),
                rs.getString("status"),
                rs.getString("feedback"),
                rs.getString("foto")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Filter: " + e.getMessage());
    }
}
}