/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riwayat_p;
import riwayat.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import ukk.session;

/**
 *
 * @author ASUS
 */
public class RiwayatAspirasiP extends javax.swing.JFrame {

    /**
     * Creates new form RiwayatAspirasi
     */
   
    PreparedStatement pst = null;
   
    public RiwayatAspirasiP() {
        initComponents();
        load_riwayat();
        this.setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    
    }
    
    public void load_riwayat() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Tanggal");
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi");
    model.addColumn("Kategori");
    model.addColumn("Status");

    try {
        int no = 1;

        Connection conn = Koneksi.Koneksi.KoneksiDB();
        PreparedStatement pst;
        ResultSet res;

        // 🔥 LOGIKA ROLE DISINI
         {

            // PELAPOR → hanya sesuai NIK
            String sql = "SELECT * FROM aspirasi "
           + "WHERE nik=? "
           + "AND (status='terimakasih' OR status='diterapkan') "
           + "ORDER BY tanggal DESC";
            pst = conn.prepareStatement(sql);
            pst.setString(1, session.getNik());
        }

        res = pst.executeQuery();

        while (res.next()) {
            model.addRow(new Object[]{
                no++,
                res.getString("tanggal"),
                res.getString("nama"),
                res.getString("isi_aspirasi"),
                res.getString("kategori"),
                res.getString("status")
            });
        }

        tb_riwayat.setModel(model);
        

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal Load Data: " + e.getMessage());
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_riwayat = new javax.swing.JTable();
        txt_cari_nama = new javax.swing.JTextField();
        cb_kategori = new javax.swing.JComboBox<>();
        tgl_dari = new com.toedter.calendar.JDateChooser();
        tgl_sampai = new com.toedter.calendar.JDateChooser();
        btn_filter = new javax.swing.JButton();
        btn_detail = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "Nama ", "Isi Aspirasi", "Kategori", "Status"
            }
        ));
        jScrollPane1.setViewportView(tb_riwayat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 1280, 520));

        txt_cari_nama.setBackground(new java.awt.Color(0,0,0,0));
        txt_cari_nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cari_nama.setBorder(null);
        txt_cari_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_namaActionPerformed(evt);
            }
        });
        txt_cari_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cari_namaKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cari_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 540, 30));

        cb_kategori.setBackground(new java.awt.Color(0,0,0,0));
        cb_kategori.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama", "isi aspirasi" }));
        cb_kategori.setBorder(null);
        jPanel1.add(cb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 60, 150, 30));
        jPanel1.add(tgl_dari, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 180, 30));
        jPanel1.add(tgl_sampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, 180, 30));

        btn_filter.setBackground(new java.awt.Color(0,0,0,0));
        btn_filter.setBorder(null);
        btn_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 90, 90, 30));

        btn_detail.setBackground(new java.awt.Color(0,0,0,0));
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });
        jPanel1.add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 120, 40));

        jButton1.setBackground(new java.awt.Color(0,0,0,0));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, 150, 40));

        jButton2.setBackground(new java.awt.Color(0,0,0,0));
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 660, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/riwayat_p/riwayat aspirasi.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filterActionPerformed
        // TODO add your handling code here :                                                                                  
    if (tgl_dari.getDate() == null || tgl_sampai.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Silakan pilih rentang tanggal!");
        return;
    }

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Tanggal");
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi");
    model.addColumn("Kategori"); // Tambahkan ini
    model.addColumn("Status");

    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dari = sdf.format(tgl_dari.getDate());
        String sampai = sdf.format(tgl_sampai.getDate());

        int no = 1;
        String sql = "SELECT * FROM aspirasi "
        + "WHERE tanggal BETWEEN ? AND ? "
        + "AND status IN ('terimakasih','diterapkan') "
        + "ORDER BY tanggal ASC";
        
        java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, dari);
        pst.setString(2, sampai);
        java.sql.ResultSet res = pst.executeQuery();

        while (res.next()) {
            model.addRow(new Object[]{
                no++, 
                res.getString("tanggal"), 
                res.getString("nama"), 
                res.getString("isi_aspirasi"), 
                res.getString("kategori"), // Tambahkan ini
                res.getString("status")
            });
        }
        tb_riwayat.setModel(model);
       

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal filter: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_filterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
    txt_cari_nama.setText("");        // Mengosongkan kolom cari
    tgl_dari.setDate(null);           // Mengosongkan filter tanggal awal
    tgl_sampai.setDate(null);         // Mengosongkan filter tanggal akhir
    cb_kategori.setSelectedIndex(0);  // Mengembalikan combobox ke pilihan pertama
    load_riwayat();                   // Memanggil kembali semua data dari database
    tb_riwayat.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        // TODO add your handling code here:                                                                                                                              
    int baris = tb_riwayat.getSelectedRow(); 
    
    if (baris != -1) {
        try {
            // Index: 0=No, 1=Tanggal, 2=Nama, 3=Isi, 4=Kategori, 5=Status
            String tgl    = tb_riwayat.getValueAt(baris, 1).toString();
            String nama   = tb_riwayat.getValueAt(baris, 2).toString();
            String isi    = tb_riwayat.getValueAt(baris, 3).toString();
            String ktgri  = tb_riwayat.getValueAt(baris, 4).toString();
            String status = tb_riwayat.getValueAt(baris, 5).toString();

            String detail = "DETAIL ASPIRASI\n"
                          + "--------------------------------------\n"
                          + "Tanggal      : " + tgl + "\n"
                          + "Nama         : " + nama + "\n"
                          + "Kategori     : " + ktgri + "\n"
                          + "Status Saat Ini : " + status + "\n"
                          + "--------------------------------------\n"
                          + "Isi Aspirasi :\n" + isi + "\n"
                          + "--------------------------------------";

            JOptionPane.showMessageDialog(this, detail, "Detail Data", JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil detail: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih baris tabel terlebih dahulu!");
    }

    }//GEN-LAST:event_btn_detailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:                                        
    // 1. Memanggil objek Menu Admin
    // Sesuaikan nama class dengan file menu utama Anda (berdasarkan gambar: menuAdmin)
    ukk.menu.menuPelapor menu = new ukk.menu.menuPelapor();
    
    // 2. Menampilkan Menu Admin
    menu.setVisible(true);
    
    // 3. Menutup halaman Riwayat Aspirasi saat ini
    this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_cari_namaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_namaKeyReleased
        // TODO add your handling code here:                                        
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Tanggal");
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi");
    model.addColumn("Kategori"); 
    model.addColumn("Status");

    try {
        String cari = txt_cari_nama.getText();
        // Query tetap sama, mencari dari depan
        String sql = "SELECT * FROM aspirasi "
        + "WHERE (nama LIKE ? OR isi_aspirasi LIKE ?) "
        + "AND status IN ('terimakasih','diterapkan') "
        + "ORDER BY tanggal DESC";

        java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, cari + "%"); 
        pst.setString(2, cari + "%"); 
        
        java.sql.ResultSet res = pst.executeQuery();

        int no = 1;
        while (res.next()) {
            model.addRow(new Object[]{
                no++, 
                res.getString("tanggal"), 
                res.getString("nama"), 
                res.getString("isi_aspirasi"), 
                res.getString("kategori"), 
                res.getString("status")
            });
        }
        tb_riwayat.setModel(model);
       

    } catch (Exception e) {
        // Untuk auto-search, sebaiknya tidak pakai JOptionPane error agar tidak mengganggu saat mengetik
        System.out.println("Error search: " + e.getMessage());
    }

    }//GEN-LAST:event_txt_cari_namaKeyReleased

    private void txt_cari_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cari_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatAspirasiP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatAspirasiP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatAspirasiP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatAspirasiP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatAspirasiP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_detail;
    private javax.swing.JButton btn_filter;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_riwayat;
    private com.toedter.calendar.JDateChooser tgl_dari;
    private com.toedter.calendar.JDateChooser tgl_sampai;
    private javax.swing.JTextField txt_cari_nama;
    // End of variables declaration//GEN-END:variables
}
