/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk.waka;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class RiwayatWaka1 extends javax.swing.JFrame {

    /**
     * Creates new form RiwayatAspirasi
     */
   
    PreparedStatement pst = null;
   
    public RiwayatWaka1() {
        initComponents();
        load_riwayat();
        this.setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    
    }
    
    public void load_riwayat() {
    DefaultTableModel model = new DefaultTableModel();

    try {
        String sql = "SELECT * FROM pengaduan "
           + "WHERE status IN ('terverifikasi','tertanggapi') "
           + "ORDER BY tgl_pengaduan ASC";

        Connection conn = Koneksi.Koneksi.KoneksiDB();
        Statement stm = conn.createStatement();
        ResultSet res = stm.executeQuery(sql);

        // 🔥 Ambil metadata kolom otomatis
        java.sql.ResultSetMetaData meta = res.getMetaData();
        int jumlahKolom = meta.getColumnCount();

        // 🔥 Tambahkan nama kolom otomatis
        for (int i = 1; i <= jumlahKolom; i++) {
            model.addColumn(meta.getColumnName(i));
        }

        // 🔥 Isi data otomatis
        while (res.next()) {
            Object[] row = new Object[jumlahKolom];
            for (int i = 0; i < jumlahKolom; i++) {
                row[i] = res.getObject(i + 1);
            }
            model.addRow(row);
        }

        tb_riwayat.setModel(model);
        lbl_total.setText("TOTAL DATA: " + tb_riwayat.getRowCount() + " pengaduan");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal Load Data: " + e.getMessage());
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_riwayat = new javax.swing.JTable();
        txt_cari_nama = new javax.swing.JTextField();
        cb_kategori = new javax.swing.JComboBox<>();
        tgl_dari = new com.toedter.calendar.JDateChooser();
        tgl_sampai = new com.toedter.calendar.JDateChooser();
        btn_filter = new javax.swing.JButton();
        lbl_total = new javax.swing.JLabel();
        btn_detail = new javax.swing.JButton();
        btn_cetak_filter = new javax.swing.JButton();
        btn_cetak_all = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "Nama ", "Isi Aspirasi", "Kategori", "Status"
            }
        ));
        jScrollPane1.setViewportView(tb_riwayat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 1620, 570));

        txt_cari_nama.setBackground(new java.awt.Color(0,0,0,0));
        txt_cari_nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cari_nama.setBorder(null);
        txt_cari_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cari_namaKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cari_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 750, 50));

        cb_kategori.setBackground(new java.awt.Color(0,0,0,0));
        cb_kategori.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama", "Kategori" }));
        cb_kategori.setBorder(null);
        jPanel1.add(cb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 190, 230, 30));

        tgl_dari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tgl_dari, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 280, 30));

        tgl_sampai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tgl_sampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 260, 30));

        btn_filter.setBackground(new java.awt.Color(0,0,0,0));
        btn_filter.setBorder(null);
        btn_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 240, 140, 50));

        lbl_total.setText("TOTAL DATA :");
        jPanel1.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 960, -1, -1));

        btn_detail.setBackground(new java.awt.Color(0,0,0,0));
        btn_detail.setBorder(null);
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });
        jPanel1.add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 950, 110, 40));

        btn_cetak_filter.setBackground(new java.awt.Color(0,0,0,0));
        btn_cetak_filter.setBorder(null);
        btn_cetak_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak_filterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetak_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 950, 120, 40));

        btn_cetak_all.setBackground(new java.awt.Color(0,0,0,0));
        btn_cetak_all.setBorder(null);
        btn_cetak_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak_allActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetak_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 950, 120, 40));

        jButton1.setBackground(new java.awt.Color(0,0,0,0));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 950, 110, 40));

        jButton2.setBackground(new java.awt.Color(0,0,0,0));
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 950, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/riwayat waka.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filterActionPerformed
        // TODO add your handling code here :                                                                                  
    if (tgl_dari.getDate() == null || tgl_sampai.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Silakan pilih rentang tanggal!");
        return;
    }

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("NIK");
    model.addColumn("tgl_pengaduan");
    model.addColumn("Isi Laporan");
    model.addColumn("Nama"); // Tambahkan ini
    model.addColumn("Foto");
    model.addColumn("Lokasi");
    model.addColumn("Kategori");
    model.addColumn("Status");
    

    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dari = sdf.format(tgl_dari.getDate());
        String sampai = sdf.format(tgl_sampai.getDate());

        int no = 1;
        String sql = "SELECT * FROM pengaduan "
           + "WHERE status IN ('terverifikasi','tertanggapi') "
           + "AND tgl_pengaduan BETWEEN ? AND ? "
           + "ORDER BY tgl_pengaduan ASC";
        
        java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, dari);
        pst.setString(2, sampai);
        java.sql.ResultSet res = pst.executeQuery();

        while (res.next()) {
            model.addRow(new Object[]{
                no++, 
                res.getString("id_pengaduan"), 
                res.getString("nik"), 
                res.getString("tgl_pengaduan"), 
                res.getString("isi_laporan"), 
                res.getString("nama"),
                res.getString("foto"),
                res.getString("lokasi"),
                res.getString("Kategori"),
                res.getString("status")
            });
        }
        tb_riwayat.setModel(model);
        lbl_total.setText("TOTAL DATA FILTER: " + tb_riwayat.getRowCount() + " Pengaduan");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal filter: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_filterActionPerformed

    private void btn_cetak_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak_filterActionPerformed
        // TODO add your handling code here:                                                                                               
    try {
        if (tgl_dari.getDate() == null || tgl_sampai.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Pilih tanggal filter dulu sebelum cetak!");
            return;
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.HashMap parameter = new java.util.HashMap();
        
        parameter.put("tgl_awal", sdf.format(tgl_dari.getDate()));
        parameter.put("tgl_akhir", sdf.format(tgl_sampai.getDate()));

        // Lokasi file pastikan huruf besar kecilnya sama dengan di folder project
        java.io.File reportFile = new java.io.File("src/report/laporan_riwayat.jasper");
        
        // PERBAIKAN: Menggunakan ukk.koneksiDB.getKoneksi()
        java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();
        
        JasperPrint jp = JasperFillManager.fillReport(reportFile.getPath(), parameter, conn);
        JasperViewer.viewReport(jp, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Cetak Gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_cetak_filterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
    txt_cari_nama.setText("");        // Mengosongkan kolom cari
    tgl_dari.setDate(null);           // Mengosongkan filter tanggal awal
    tgl_sampai.setDate(null);         // Mengosongkan filter tanggal akhir
    cb_kategori.setSelectedIndex(0);  // Mengembalikan combobox ke pilihan pertama
    load_riwayat();                   // Memanggil kembali semua data dari database

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        // TODO add your handling code here:                                                                                                                              
    int row = tb_riwayat.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    try {

        StringBuilder detail = new StringBuilder();
        String pathFoto = null;

        detail.append("DETAIL DATA PENGADUAN\n");
        detail.append("====================================\n");

        for (int i = 0; i < tb_riwayat.getColumnCount(); i++) {

            String namaKolom = tb_riwayat.getColumnName(i);
            Object value = tb_riwayat.getValueAt(row, i);

            if (namaKolom.equalsIgnoreCase("foto")) {
                pathFoto = value == null ? null : value.toString();
            } else {
                detail.append(namaKolom)
                      .append(" : ")
                      .append(value == null ? "-" : value.toString())
                      .append("\n");
            }
        }

        detail.append("====================================");

        // ================= PANEL UTAMA =================
        JPanel panelUtama = new JPanel(new BorderLayout(20, 10));

        // ================= TEXT DETAIL =================
        JTextArea textArea = new JTextArea(detail.toString());
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);

        JScrollPane scrollText = new JScrollPane(textArea);
        scrollText.setPreferredSize(new Dimension(350, 250));

        panelUtama.add(scrollText, BorderLayout.CENTER);

        // ================= FOTO =================
        if (pathFoto != null && !pathFoto.isEmpty()) {

            java.io.File file = new java.io.File(pathFoto);

            if (file.exists()) {

                ImageIcon icon = new ImageIcon(pathFoto);

                Image img = icon.getImage().getScaledInstance(250, 250, Image.SCALE_SMOOTH);
                JLabel lblFoto = new JLabel(new ImageIcon(img));
                lblFoto.setHorizontalAlignment(JLabel.CENTER);

                panelUtama.add(lblFoto, BorderLayout.EAST);

            } else {
                panelUtama.add(new JLabel("Foto tidak ditemukan"), BorderLayout.EAST);
            }
        }

        JOptionPane.showMessageDialog(this, panelUtama,
                "Detail Pengaduan",
                JOptionPane.PLAIN_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Gagal tampil detail: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_detailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:                                        
    // 1. Memanggil objek Menu Admin
    // Sesuaikan nama class dengan file menu utama Anda (berdasarkan gambar: menuAdmin)
    ukk.menu.menuWaka waka = new ukk.menu.menuWaka();
    
    // 2. Menampilkan Menu waka
    waka.setVisible(true);
    
    // 3. Menutup halaman Riwayat Aspirasi saat ini
    this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_cetak_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak_allActionPerformed
        // TODO add your handling code here:                                            
     // 1. Pastikan koneksi tidak null
  Connection conn = Koneksi.Koneksi.KoneksiDB(); 
if (conn == null) {
    JOptionPane.showMessageDialog(null, "Koneksi Database Gagal!");
    return;
}

String sql = "SELECT " +
" pengaduan.`id_pengaduan` AS pengaduan_id_pengaduan, " +
" pengaduan.`nik` AS pengaduan_nik, " +
" pengaduan.`tgl_pengaduan` AS pengaduan_tgl_pengaduan, " +
" pengaduan.`isi_laporan` AS pengaduan_isi_laporan, " +
" pengaduan.`nama` AS pengaduan_nama, " +
" pengaduan.`foto` AS pengaduan_foto, " +
" pengaduan.`lokasi` AS pengaduan_lokasi, " +
" pengaduan.`Kategori` AS pengaduan_Kategori, " +
" pengaduan.`status` AS pengaduan_status, " +
" tanggapan.`id_tanggapan` AS tanggapan_id_tanggapan, " +
" tanggapan.`nik` AS tanggapan_nik, " +
" tanggapan.`nama` AS tanggapan_nama, " +
" tanggapan.`isi_pengaduan` AS tanggapan_isi_pengaduan, " +
" tanggapan.`feedback` AS tanggapan_feedback, " +
" tanggapan.`status` AS tanggapan_status, " +
" tanggapan.`tanggal` AS tanggapan_tanggal, " +
" tanggapan.`foto` AS tanggapan_foto, " +
" tanggapan.`id_pengaduan` AS tanggapan_id_pengaduan, " +
" tanggapan.`tgl_tang` AS tanggapan_tgl_tang, " +
" tanggapan.`kategori` AS tanggapan_kategori, " +
" tanggapan.`lokasi` AS tanggapan_lokasi, " +
" tanggapan.`id_petugas` AS tanggapan_id_petugas " +
"FROM pengaduan " +
"INNER JOIN tanggapan ON pengaduan.`id_pengaduan` = tanggapan.`id_pengaduan`";

try {

    PreparedStatement pst = conn.prepareStatement(sql);
    ResultSet rp = pst.executeQuery();

    JRResultSetDataSource jrRS = new JRResultSetDataSource(rp);

    JasperReport jasperReport = JasperCompileManager.compileReport(
            "D:/buiza/ukk/src/report/LAWAKALL.jrxml");

    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);

    // FULL SCREEN VIEWER
    JasperViewer viewer = new JasperViewer(jasperPrint, false);
    viewer.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    viewer.setFitPageZoomRatio();
    viewer.setVisible(true);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Laporan gak ada: " + e.getMessage());
    e.printStackTrace();
}
    }//GEN-LAST:event_btn_cetak_allActionPerformed

    private void txt_cari_namaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_namaKeyReleased
        // TODO add your handling code here:                                        
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("ID");
    model.addColumn("NIK");
    model.addColumn("tgl_pengaduan");
    model.addColumn("Isi Laporan");
    model.addColumn("Nama"); // Tambahkan ini
    model.addColumn("Foto");
    model.addColumn("Lokasi");
    model.addColumn("Kategori");
    model.addColumn("Status");

    try {
        String cari = txt_cari_nama.getText();
        // Query tetap sama, mencari dari depan
        String sql = "SELECT * FROM pengaduan "
           + "WHERE status IN ('terverifikasi','tertanggapi') "
           + "AND (nama LIKE ? OR kategori LIKE ? OR isi_laporan LIKE ?) "
           + "ORDER BY tgl_pengaduan ASC";

        java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, cari + "%"); 
        pst.setString(2, cari + "%"); 
        pst.setString(3, cari + "%"); 
        
        java.sql.ResultSet res = pst.executeQuery();

        int no = 1;
        while (res.next()) {
            model.addRow(new Object[]{
                no++, 
                res.getString("id_pengaduan"), 
                res.getString("nik"), 
                res.getString("tgl_pengaduan"), 
                res.getString("isi_laporan"), 
                res.getString("nama"),
                res.getString("foto"),
                res.getString("lokasi"),
                res.getString("Kategori"),
                res.getString("status")
            });
        }
        tb_riwayat.setModel(model);
        lbl_total.setText("TOTAL HASIL: " + tb_riwayat.getRowCount() + " Pengaduan");

    } catch (Exception e) {
        // Untuk auto-search, sebaiknya tidak pakai JOptionPane error agar tidak mengganggu saat mengetik
        System.out.println("Error search: " + e.getMessage());
    }

    }//GEN-LAST:event_txt_cari_namaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatWaka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatWaka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatWaka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatWaka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatWaka1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak_all;
    private javax.swing.JButton btn_cetak_filter;
    private javax.swing.JButton btn_detail;
    private javax.swing.JButton btn_filter;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tb_riwayat;
    private com.toedter.calendar.JDateChooser tgl_dari;
    private com.toedter.calendar.JDateChooser tgl_sampai;
    private javax.swing.JTextField txt_cari_nama;
    // End of variables declaration//GEN-END:variables
}
