/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk.pelapor;
import ukk.admin.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.io.File;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDialog;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import ukk.session;

/**
 *
 * @author ASUS
 */
public class Aspirasi_peng extends javax.swing.JFrame {

    /**
     * Creates new form Aspirasi1
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    private DefaultTableModel model;
    
    private void setTanggalHariIni() {
    txt_tanggal.setDate(new Date());
    txt_tanggal.getDateEditor().setEnabled(false);
    txt_tanggal.getCalendarButton().setEnabled(false);}
    
    public Aspirasi_peng() {
        initComponents();
        txt_nik.setText(session.getNik());
        txt_nik.setEditable(false);

        //setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        conn = Koneksi.Koneksi.KoneksiDB(); //javaConnect = nama file || Connection = nama method
  
        setTanggalHariIni();
        tampilidaspirasi();

        
        //memberi penamaan pada judul kolom ; 
        model = new DefaultTableModel();
        tbAspirasi.setModel(model);
        model.addColumn("id aspirasi");
        model.addColumn("nik");
        model.addColumn("nama");
        model.addColumn("Tanggal aspirasi");
        model.addColumn("Isi aspirasi");
        model.addColumn("kategori");
        model.addColumn("status");
        
        
        tampilkan_data();//memanggil method getdata
       }
    
 //menampilkan data dr tabel ke masing-masing komponen cara 2
   void pilihData() {
       int i = tbAspirasi.getSelectedRow();
      // txt_pengaduan.setText(model.getValueAt(i, 0).toString());
       txt_nik.setText(model.getValueAt(i, 0).toString());
       txt_nama.setText(model.getValueAt(i, 1).toString());
       txt_isi.setText(model.getValueAt(i, 2).toString());
       
   } 
   
   void bersih() {
       //txt_pengaduan.setText("");
       txt_nik.setText("");
       txt_nama.setText("");
       txt_isi.setText(""); 
   }

      void tampilidaspirasi() {
    try {
        String sql = "SELECT IFNULL(MAX(id_aspirasi), 0) + 1 AS id FROM aspirasi";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();

        if (rs.next()) {
            txt_id.setText(rs.getString("id"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
      
        private void hapusAspirasi() {

    // Cek apakah ada data dipilih
    if (txt_id.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Pilih data aspirasi terlebih dahulu!");
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION
    );

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {

            // Hanya boleh hapus jika id DAN nik sesuai login
            String sql = "DELETE FROM aspirasi WHERE id_aspirasi = ? AND nik = ?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txt_id.getText());
            pst.setString(2, session.getNik()); // NIK user login

            int hasil = pst.executeUpdate();

            if (hasil > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                tampilkan_data();
                bersih();
            } else {
                JOptionPane.showMessageDialog(this, "Anda tidak berhak menghapus data ini!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage());
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nik = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_isi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAspirasi = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        cb_filter = new javax.swing.JComboBox<>();
        txt_id = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();
        txt_tanggal = new com.toedter.calendar.JDateChooser();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        cb_kategori = new javax.swing.JComboBox<>();
        cb_statusfil = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nik.setBackground(new java.awt.Color(0,0,0,0));
        txt_nik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nik.setBorder(null);
        txt_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nikActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 400, 50));

        txt_nama.setEditable(false);
        txt_nama.setBackground(new java.awt.Color(0,0,0,0));
        txt_nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nama.setBorder(null);
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 400, 50));

        txt_isi.setBackground(new java.awt.Color(0,0,0,0));
        txt_isi.setColumns(20);
        txt_isi.setRows(5);
        txt_isi.setBorder(null);
        jScrollPane1.setViewportView(txt_isi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 400, 150));

        tbAspirasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NISN", "Nama", "Tanggal", "Isi Aspirasi", "Status", "Kategori"
            }
        ));
        tbAspirasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAspirasiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbAspirasi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 1000, 660));

        txt_cari.setBackground(new java.awt.Color(0,0,0,0));
        txt_cari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cari.setBorder(null);
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 720, 40));

        cb_filter.setBackground(new java.awt.Color(0,0,0,0));
        cb_filter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NIK", "NISN", "Nama", "Kategori" }));
        cb_filter.setBorder(null);
        cb_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_filterActionPerformed(evt);
            }
        });
        jPanel1.add(cb_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 180, 110, 40));

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(0,0,0,0));
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_id.setBorder(null);
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 410, 50));

        btn_refresh.setBackground(new java.awt.Color(0,0,0,0));
        btn_refresh.setBorder(null);
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel1.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 790, 70, 40));

        txt_tanggal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txt_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 400, 40));

        btn_simpan.setBackground(new java.awt.Color(0,0,0,0));
        btn_simpan.setBorder(null);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 790, 80, 40));

        btn_hapus.setBackground(new java.awt.Color(0,0,0,0));
        btn_hapus.setBorder(null);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 790, 80, 40));

        cb_kategori.setBackground(new java.awt.Color(0,0,0,0));
        cb_kategori.setEditable(true);
        cb_kategori.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_kategori.setForeground(new java.awt.Color(102, 102, 102));
        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hardware PC Lab", "Software & Library", "Jaringan & Internet", "Sarana Ruang Praktik", "Kelistrikan & Kabel" }));
        cb_kategori.setBorder(null);
        cb_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kategoriActionPerformed(evt);
            }
        });
        jPanel1.add(cb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 400, 50));

        cb_statusfil.setBackground(new java.awt.Color(0,0,0,0));
        cb_statusfil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_statusfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "terimakasih", "diterapkan" }));
        cb_statusfil.setBorder(null);
        cb_statusfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_statusfilActionPerformed(evt);
            }
        });
        jPanel1.add(cb_statusfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 180, 150, 40));

        jButton1.setBackground(new java.awt.Color(0,0,0,0));
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 110, 60));

        jButton2.setBackground(new java.awt.Color(0,0,0,0));
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 790, 80, 40));

        jButton3.setBackground(new java.awt.Color(0,0,0,0));
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 790, 90, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelapor aspirasi.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_filterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_filterActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:                                                                             
           String tampilan = "yyyy-MM-dd";
    SimpleDateFormat fm = new SimpleDateFormat(tampilan);
    String tanggal = String.valueOf(fm.format(txt_tanggal.getDate()));

    try {
        String sql = "UPDATE aspirasi SET isi_aspirasi = ?, kategori = ? WHERE id_aspirasi = ? AND nik = ?";
        pst = conn.prepareStatement(sql);

        pst.setString(1, txt_isi.getText());
        pst.setString(2, cb_kategori.getSelectedItem().toString());
        pst.setString(3, txt_id.getText());
        pst.setString(4, session.getNik());

        int hasil = pst.executeUpdate();

        if (hasil > 0) {
            JOptionPane.showMessageDialog(null, "Update berhasil!");
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan / bukan milik anda!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }

    tampilkan_data();
    bersih();

    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:                                       
   ukk.menu.menuPelapor menu = new ukk.menu.menuPelapor();
    
    // 2. Menampilkan Menu Admin
    menu.setVisible(true);
    
    // 3. Menutup halaman Riwayat Aspirasi saat ini
    this.dispose();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbAspirasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAspirasiMouseClicked
        // TODO add your handling code here:                                                                                                                                                                                                                                                                                  
    int i = tbAspirasi.getSelectedRow();
    if (i != -1) {
        txt_id.setText(tbAspirasi.getValueAt(i, 0).toString());
        txt_nik.setText(tbAspirasi.getValueAt(i, 1).toString());
        txt_nama.setText(tbAspirasi.getValueAt(i, 2).toString());
        txt_isi.setText(tbAspirasi.getValueAt(i, 3).toString());
        
        // Mengisi data kategori ke ComboBox
        cb_kategori.setSelectedItem(tbAspirasi.getValueAt(i, 4).toString());
        
        // KUNCI DISINI: Agar admin tidak bisa mengubah
      //  cb_kategori.setEnabled(false); 
        
//        cb_status.setSelectedItem(tbAspirasi.getValueAt(i, 5).toString());
        
        try {
            java.util.Date date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tbAspirasi.getValueAt(i, 6).toString());
            txt_tanggal.setDate(date);
        } catch (Exception e) {
            txt_tanggal.setDate(null);
        }
    }


    }//GEN-LAST:event_tbAspirasiMouseClicked

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nikActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:                                                                                                                                                                                                                        
    // 1. Bersihkan inputan
    txt_id.setText("");           
    txt_nik.setText("");         
    txt_nama.setText("");         
    txt_tanggal.setDate(null);    
    txt_isi.setText("");          
//    cb_status.setSelectedIndex(0); 
    txt_cari.setText("");         

    // 2. Pengaturan Kunci
    txt_nik.setEditable(false); // Admin biasanya tidak boleh edit identitas
    txt_nama.setEditable(false);
    txt_isi.setEditable(true);
    txt_tanggal.setEnabled(true);
    
    // Kategori tetap dikunci (false)
    cb_kategori.setEnabled(true); 

    // 3. Update Tabel (Pastikan kolom kategori ada)
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID"); 
    model.addColumn("NIK / NISN"); 
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi"); // Sesuaikan urutan dengan tampilkan_data
    model.addColumn("Kategori");
    model.addColumn("Status");
    model.addColumn("Tanggal");

    try {
    java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();

    String sql = "SELECT * FROM aspirasi WHERE nik = ? ORDER BY id_aspirasi ASC";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, session.getNik());

    java.sql.ResultSet res = pst.executeQuery();

    while(res.next()){
        model.addRow(new Object[]{
            res.getString("id_aspirasi"),
            res.getString("nik"),
            res.getString("nama"),
            res.getString("isi_aspirasi"),
            res.getString("kategori"),
            res.getString("status"),
            res.getString("tanggal")
        });
    }

    tbAspirasi.setModel(model);

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal Refresh: " + e.getMessage());
}
tampilidaspirasi();

    }//GEN-LAST:event_btn_refreshActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:                                  
    cariData(); // Memanggil fungsi pencarian setiap tombol keyboard dilepas
    }//GEN-LAST:event_txt_cariKeyReleased

    private void cb_statusfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_statusfilActionPerformed
        // TODO add your handling code here:
        filterStatus();
        
    }//GEN-LAST:event_cb_statusfilActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
                String sql = "select * from pelapor where nik='" + txt_nik.getText() + "'";  
        try {
            
            
            pst = conn.prepareStatement(sql);
            rs  = pst.executeQuery();
            
            if (rs.next()) {
                String addl = rs.getString("nama");
                txt_nama.setText(addl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String tampilan="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal=String.valueOf(fm.format(txt_tanggal.getDate()));
     
        try{
          String sql = "INSERT INTO aspirasi (nik, tanggal, isi_aspirasi, nama, kategori, status) VALUES (?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);

            pst.setString(1, txt_nik.getText());
            pst.setString(2, tanggal);
            pst.setString(3, txt_isi.getText());
            pst.setString(4, txt_nama.getText());
            pst.setString(5, cb_kategori.getSelectedItem().toString());
            pst.setString(6, "menunggu");

           pst.execute();
           JOptionPane.showMessageDialog(null, "saved");
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
       }
       tampilkan_data();
       bersih();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_kategoriActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        hapusAspirasi();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aspirasi_peng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aspirasi_peng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aspirasi_peng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aspirasi_peng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aspirasi_peng().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cb_filter;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JComboBox<String> cb_statusfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbAspirasi;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextArea txt_isi;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nik;
    private com.toedter.calendar.JDateChooser txt_tanggal;
    // End of variables declaration//GEN-END:variables
  private void tampilkan_data() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");              
    model.addColumn("NIK / NISN");
    model.addColumn("Nama");           
    model.addColumn("Isi Aspirasi");   
    model.addColumn("Kategori"); // <--- Tambah Kolom Baru
    model.addColumn("Status");         
    model.addColumn("Tanggal"); 

    try {
        //java.sql.Connection conn = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
//        String sql = "SELECT * FROM aspirasi ORDER BY tanggal ASC";
//        java.sql.ResultSet res = conn.createStatement().executeQuery(sql);
        String sql = "SELECT * FROM aspirasi WHERE nik = ? ORDER BY tanggal ASC";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, session.getNik());
        ResultSet res = pst.executeQuery();
        
        while(res.next()){
            String nik = res.getString("nik");
           ///// String nisn = res.getString("nisn");
            String identitasTampil = res.getString("nik");


            model.addRow(new Object[]{
                res.getString("id_aspirasi"),
                identitasTampil,
                res.getString("nama"), 
                res.getString("isi_aspirasi"),
                res.getString("kategori"), // <--- Ambil data kategori
                res.getString("status"),
                res.getString("tanggal") 
            });
        }
        tbAspirasi.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Tampil: " + e.getMessage());
    }
}
//  
  
 private void cariData() {
    DefaultTableModel model = new DefaultTableModel();
    // 1. Tata letak kolom konsisten
    model.addColumn("ID");              // 0
    model.addColumn("NIK / NISN");      // 1
    model.addColumn("Nama");            // 2
    model.addColumn("Isi Aspirasi");    // 3
    model.addColumn("Kategori");        // 4
    model.addColumn("Status");          // 5
    model.addColumn("Tanggal");         // 6

    try {
        java.sql.Connection conn = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
        String cari = txt_cari.getText();
        String filter = cb_filter.getSelectedItem().toString();
        String sql = "";

        // 2. Logika Query SQL (Tetap sama)
        if (filter.equals("ID")) {
            sql = "SELECT * FROM aspirasi WHERE id_aspirasi LIKE ?";
        } else if (filter.equals("NIK")) {
            sql = "SELECT * FROM aspirasi WHERE nik LIKE ?";
        } else if (filter.equals("Nama")) {
            sql = "SELECT * FROM aspirasi WHERE nama LIKE ?"; 
        } else if (filter.equals("Kategori")) {
            sql = "SELECT * FROM aspirasi WHERE kategori LIKE ?";
        } else {
            // Pencarian Umum (Semua kolom dicari dari depan)
            sql = "SELECT * FROM aspirasi WHERE nama LIKE ? OR nik LIKE ? OR kategori LIKE ?";
        }
        
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        // 3. SEMUA menerapkan pencarian dari DEPAN (Tanpa tanda % di awal)
        if (filter.equals("Nama") || filter.equals("ID") || filter.equals("NIK") || filter.equals("Kategori")) {
            pst.setString(1, cari + "%"); 
        } else {
            // Untuk pencarian "Semua" - semua parameter diset cari + "%"
            pst.setString(1, cari + "%"); // nama
            pst.setString(2, cari + "%"); // nik
           // pst.setString(3, cari + "%"); // nisn
            pst.setString(3, cari + "%"); // kategori
        }

        java.sql.ResultSet res = pst.executeQuery();
        
        while(res.next()){
            String vNik = res.getString("nik");
           // String vNisn = res.getString("nisn");
           String identitasTampil = res.getString("nik");


            model.addRow(new Object[]{
                res.getString("id_aspirasi"),
                identitasTampil,
                res.getString("nama"),
                res.getString("isi_aspirasi"),
                res.getString("kategori"), // Tetap rapi di index 4
                res.getString("status"),
                res.getString("tanggal")
            });
        }
        tbAspirasi.setModel(model);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Mencari: " + e.getMessage());
    }
}


 
private void filterStatus() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("NIK / NISN");
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi");
    model.addColumn("Kategori");
    model.addColumn("Status");
    model.addColumn("Tanggal");

   // .trim() akan menghapus spasi di depan atau di belakang teks
String statusPilihan = cb_statusfil.getSelectedItem().toString().trim(); 

try {
    java.sql.Connection conn = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
    
    // Gunakan query ini agar lebih aman dari spasi tersembunyi
    String sql = "SELECT * FROM aspirasi WHERE status = ? ORDER BY tanggal DESC";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, statusPilihan); 
    
    java.sql.ResultSet res = pst.executeQuery();
   
        
        boolean dataDitemukan = false;
        while(res.next()){
            dataDitemukan = true;
            String vNik = res.getString("nik");
          //  String vNisn = res.getString("nisn");
            String identitasTampil = res.getString("nik");


            model.addRow(new Object[]{
                res.getString("id_aspirasi"),
                identitasTampil,
                res.getString("nama"),
                res.getString("isi_aspirasi"),
                res.getString("kategori"), 
                res.getString("status"),
                res.getString("tanggal")
            });
        }
        tbAspirasi.setModel(model);

        if (!dataDitemukan) {
            System.out.println("Data dengan status " + statusPilihan + " tidak ditemukan di DB.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menyaring status: " + e.getMessage());
    }
}
   
    public void cetakStruk(String idAspirasi) {
    // Tambahkan WHERE id_aspirasi = ? di akhir query
    String sql = "SELECT\n" +
"     aspirasi.`id_aspirasi` AS aspirasi_id_aspirasi,\n" +
"     aspirasi.`nik` AS aspirasi_nik,\n" +
"     aspirasi.`nama` AS aspirasi_nama,\n" +
"     aspirasi.`isi_aspirasi` AS aspirasi_isi_aspirasi,\n" +
"     aspirasi.`status` AS aspirasi_status,\n" +
"     aspirasi.`tanggal` AS aspirasi_tanggal\n" + // Baris feedback/tanggapan dihapus
"FROM\n" +
"     `aspirasi` aspirasi\n" +
"WHERE aspirasi.`id_aspirasi` = ?";
    
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rp = null;
    
    try {
        // Gunakan koneksi yang sudah kamu buat agar konsisten
        connection = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
        
        pst = connection.prepareStatement(sql, 
        ResultSet.TYPE_SCROLL_INSENSITIVE, 
        ResultSet.CONCUR_READ_ONLY);
        pst.setString(1, idAspirasi); // Memasukkan ID ke tanda tanya (?)
        rp = pst.executeQuery();
        
        if (rp.next()) { // Cek apakah data ada
            // Reset ResultSet ke awal sebelum dikirim ke Jasper
            rp.beforeFirst(); 
            
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rp);
            // Pastikan path file .jrxml benar
            JasperReport jasperReport = JasperCompileManager.compileReport("G:\\UKKAspirasi\\src\\ReportUKK\\laporan_id.jrxml");
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);
            
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            viewer.setTitle("Laporan Aspirasi");
            viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(0, 0, screenSize.width, screenSize.height);
            viewer.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan di database.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Cetak: " + e.getMessage());
        e.printStackTrace();
    } finally {
        // Resource closing ditangani agar tidak bocor memory
        try { if (rp != null) rp.close(); } catch (Exception e) {}
        try { if (pst != null) pst.close(); } catch (Exception e) {}
    }
}

}
