/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk.admin;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.io.File;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JDialog;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author ASUS
 */
public class Aspirasi1 extends javax.swing.JFrame {

    /**
     * Creates new form Aspirasi1
     */
    
    PreparedStatement pst = null;
    
    public Aspirasi1() {
        initComponents();
        tampilkan_data();
        this.setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nik = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_isi = new javax.swing.JTextArea();
        cb_status = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAspirasi = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        cb_filter = new javax.swing.JComboBox<>();
        txt_id = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        cb_kategori = new javax.swing.JComboBox<>();
        cb_statusfil = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nik.setEditable(false);
        txt_nik.setBackground(new java.awt.Color(0,0,0,0));
        txt_nik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nik.setBorder(null);
        txt_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nikActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 380, 40));

        txt_nama.setEditable(false);
        txt_nama.setBackground(new java.awt.Color(0,0,0,0));
        txt_nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nama.setBorder(null);
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 380, 50));

        txt_isi.setEditable(false);
        txt_isi.setBackground(new java.awt.Color(0,0,0,0));
        txt_isi.setColumns(20);
        txt_isi.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txt_isi.setRows(5);
        txt_isi.setBorder(null);
        jScrollPane1.setViewportView(txt_isi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 390, 100));

        cb_status.setBackground(new java.awt.Color(0,0,0,0));
        cb_status.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "terimakasih", "diterapkan", " " }));
        cb_status.setBorder(null);
        cb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_statusActionPerformed(evt);
            }
        });
        jPanel1.add(cb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 690, 390, 50));

        tbAspirasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NISN", "Nama", "Tanggal", "Isi Aspirasi", "Status", "Kategori"
            }
        ));
        tbAspirasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAspirasiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbAspirasi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 1000, 650));

        txt_cari.setBackground(new java.awt.Color(0,0,0,0));
        txt_cari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cari.setBorder(null);
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 680, 40));

        cb_filter.setBackground(new java.awt.Color(0,0,0,0));
        cb_filter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NIK", "NISN", "Nama", "Kategori" }));
        cb_filter.setBorder(null);
        cb_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_filterActionPerformed(evt);
            }
        });
        jPanel1.add(cb_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 230, 100, 40));

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(0,0,0,0));
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_id.setBorder(null);
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 380, 40));

        btn_refresh.setBackground(new java.awt.Color(0,0,0,0));
        btn_refresh.setBorder(null);
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel1.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 780, 70, 40));

        btn_simpan.setBackground(new java.awt.Color(0,0,0,0));
        btn_simpan.setBorder(null);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 780, 80, 40));

        btn_hapus.setBackground(new java.awt.Color(0,0,0,0));
        btn_hapus.setBorder(null);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 780, 80, 40));

        cb_kategori.setBackground(new java.awt.Color(0,0,0,0));
        cb_kategori.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_kategori.setForeground(new java.awt.Color(102, 102, 102));
        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hardware PC Lab", "Software & Library", "Jaringan & Internet", "Sarana Ruang Praktik", "Kelistrikan & Kabel" }));
        cb_kategori.setBorder(null);
        jPanel1.add(cb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 390, 50));

        cb_statusfil.setBackground(new java.awt.Color(0,0,0,0));
        cb_statusfil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_statusfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "terimakasih", "diterapkan" }));
        cb_statusfil.setBorder(null);
        cb_statusfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_statusfilActionPerformed(evt);
            }
        });
        jPanel1.add(cb_statusfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 230, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_new/aspirasi tan.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 1920, 1090));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_filterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_filterActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:                                                                             
  try {
    String id_aspirasi = txt_id.getText(); 
    String status_baru = cb_status.getSelectedItem().toString();

    if (id_aspirasi.equals("")) {
        JOptionPane.showMessageDialog(this, "Pilih data di tabel dahulu!");
        return;
    }

    Connection conn = Koneksi.Koneksi.KoneksiDB();

    String sqlUpdate = "UPDATE aspirasi "
                     + "SET status=?, tanggal_tang=CURDATE() "
                     + "WHERE id_aspirasi=?"; 

    PreparedStatement pstUp = conn.prepareStatement(sqlUpdate);
    pstUp.setString(1, status_baru);
    pstUp.setString(2, id_aspirasi);

    int hasil = pstUp.executeUpdate();

    if (hasil > 0) {
        JOptionPane.showMessageDialog(null, "Status & tanggal tanggapan berhasil diperbarui!");
        tampilkan_data();
        bersih();
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal Update: " + e.getMessage());
}
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:                                       
   ukk.menu.menuAdmin menu = new ukk.menu.menuAdmin();
    
    // 2. Menampilkan Menu Admin
    menu.setVisible(true);
    
    // 3. Menutup halaman Riwayat Aspirasi saat ini
    this.dispose();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbAspirasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAspirasiMouseClicked
        // TODO add your handling code here:                                                                                                                                                                                                                                                                                  
    int i = tbAspirasi.getSelectedRow();
    if (i != -1) {
        txt_id.setText(tbAspirasi.getValueAt(i, 0).toString());
        txt_nik.setText(tbAspirasi.getValueAt(i, 1).toString());
        txt_nama.setText(tbAspirasi.getValueAt(i, 2).toString());
        txt_isi.setText(tbAspirasi.getValueAt(i, 3).toString());
        
        // Mengisi data kategori ke ComboBox
        cb_kategori.setSelectedItem(tbAspirasi.getValueAt(i, 4).toString());
        
        // KUNCI DISINI: Agar admin tidak bisa mengubah
        cb_kategori.setEnabled(false); 
        
        cb_status.setSelectedItem(tbAspirasi.getValueAt(i, 5).toString());
        
//        try {
//            java.util.Date date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tbAspirasi.getValueAt(i, 6).toString());
//            txt_tanggal.setDate(date);
//        } catch (Exception e) {
//            txt_tanggal.setDate(null);
//        }
    }


    }//GEN-LAST:event_tbAspirasiMouseClicked

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void cb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_statusActionPerformed

    private void txt_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nikActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:                                                                                                                                                                                                                        
    // 1. Bersihkan inputan
    txt_id.setText("");           
    txt_nik.setText("");         
    txt_nama.setText("");         
    
    txt_isi.setText("");          
    cb_status.setSelectedIndex(0); 
    txt_cari.setText("");         

    // 2. Pengaturan Kunci
    txt_nik.setEditable(false); // Admin biasanya tidak boleh edit identitas
    txt_nama.setEditable(false);
    txt_isi.setEditable(false);
   
    
    // Kategori tetap dikunci (false)
    cb_kategori.setEnabled(false); 

    // 3. Update Tabel (Pastikan kolom kategori ada)
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID"); 
    model.addColumn("NIK / NISN"); 
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi"); // Sesuaikan urutan dengan tampilkan_data
    model.addColumn("Kategori");
    model.addColumn("Tanggal");
    model.addColumn("Status");
    

    try {
        java.sql.Connection conn = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
        String sql = "SELECT * FROM aspirasi WHERE status='menunggu' ORDER BY id_aspirasi DESC";
        java.sql.ResultSet res = conn.createStatement().executeQuery(sql);
        
        while(res.next()){
            String vNik = res.getString("nik");
            //String vNisn = res.getString("nisn");
            String identitasTampil = res.getString("nik");


            model.addRow(new Object[]{
                res.getString("id_aspirasi"),
                identitasTampil,                   
                res.getString("nama"),        
                res.getString("isi_aspirasi"),
                res.getString("kategori"), // Ambil dari DB
                res.getString("tanggal"),   
                res.getString("status")
                  
            });
        }
        tbAspirasi.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal Refresh: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_refreshActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:                                  
    cariData(); // Memanggil fungsi pencarian setiap tombol keyboard dilepas
    }//GEN-LAST:event_txt_cariKeyReleased

    private void cb_statusfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_statusfilActionPerformed
        // TODO add your handling code here:
        filterStatus();
        
    }//GEN-LAST:event_cb_statusfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aspirasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aspirasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aspirasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aspirasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aspirasi1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cb_filter;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JComboBox<String> cb_statusfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbAspirasi;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextArea txt_isi;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nik;
    // End of variables declaration//GEN-END:variables
  private void tampilkan_data() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");              
    model.addColumn("NIK / NISN");
    model.addColumn("Nama");           
    model.addColumn("Isi Aspirasi");   
    model.addColumn("Kategori");
    model.addColumn("Tanggal"); 
    model.addColumn("Status");         

    try {
        java.sql.Connection conn = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
        String sql = "SELECT * FROM aspirasi WHERE status='menunggu' ORDER BY tanggal ASC";
        java.sql.ResultSet res = conn.createStatement().executeQuery(sql);
        
        while(res.next()){
            String identitasTampil = res.getString("nik");

            model.addRow(new Object[]{
                res.getString("id_aspirasi"),
                identitasTampil,
                res.getString("nama"), 
                res.getString("isi_aspirasi"),
                res.getString("kategori"),
                res.getString("tanggal"),
                res.getString("status")
            });
        }
        tbAspirasi.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Tampil: " + e.getMessage());
    }
}
  
  
 private void cariData() {
    DefaultTableModel model = new DefaultTableModel();
    // 1. Tata letak kolom konsisten
    model.addColumn("ID");              // 0
    model.addColumn("NIK / NISN");      // 1
    model.addColumn("Nama");            // 2
    model.addColumn("Isi Aspirasi");    // 3
    model.addColumn("Kategori");        // 4
    model.addColumn("Tanggal");         // 5
    model.addColumn("Status");          // 6
    

    try {
        java.sql.Connection conn = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
        String cari = txt_cari.getText();
        String filter = cb_filter.getSelectedItem().toString();
        String sql = "";

        // 2. Logika Query SQL (Tetap sama)
        if (filter.equals("ID")) {
            sql = "SELECT * FROM aspirasi WHERE id_aspirasi LIKE ?";
        } else if (filter.equals("NIK")) {
            sql = "SELECT * FROM aspirasi WHERE nik LIKE ?";
        } else if (filter.equals("Nama")) {
            sql = "SELECT * FROM aspirasi WHERE nama LIKE ?"; 
        } else if (filter.equals("Kategori")) {
            sql = "SELECT * FROM aspirasi WHERE kategori LIKE ?";
        } else {
            // Pencarian Umum (Semua kolom dicari dari depan)
            sql = "String sql = \"SELECT * FROM aspirasi WHERE status='menunggu' AND nama LIKE ?\"; ?";
        }
        
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        // 3. SEMUA menerapkan pencarian dari DEPAN (Tanpa tanda % di awal)
        if (filter.equals("Nama") || filter.equals("ID") || filter.equals("NIK") || filter.equals("Kategori")) {
            pst.setString(1, cari + "%"); 
        } else {
            // Untuk pencarian "Semua" - semua parameter diset cari + "%"
            pst.setString(1, cari + "%"); // nama
            pst.setString(2, cari + "%"); // nik
           // pst.setString(3, cari + "%"); // nisn
            pst.setString(3, cari + "%"); // kategori
        }

        java.sql.ResultSet res = pst.executeQuery();
        
        while(res.next()){
            String vNik = res.getString("nik");
           // String vNisn = res.getString("nisn");
           String identitasTampil = res.getString("nik");


            model.addRow(new Object[]{
                res.getString("id_aspirasi"),
                identitasTampil,
                res.getString("nama"),
                res.getString("isi_aspirasi"),
                res.getString("kategori"), // Tetap rapi di index 4
                res.getString("tanggal"),
                res.getString("status")
            });
        }
        tbAspirasi.setModel(model);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Mencari: " + e.getMessage());
    }
}


 
private void filterStatus() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("NIK / NISN");
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi");
    model.addColumn("Kategori");
    model.addColumn("Tanggal");
    model.addColumn("Status");
    

   // .trim() akan menghapus spasi di depan atau di belakang teks
String statusPilihan = cb_statusfil.getSelectedItem().toString().trim(); 

try {
    java.sql.Connection conn = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
    
    // Gunakan query ini agar lebih aman dari spasi tersembunyi
    String sql = "SELECT * FROM aspirasi WHERE status = ? ORDER BY tanggal DESC";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, statusPilihan); 
    
    java.sql.ResultSet res = pst.executeQuery();
   
        
        boolean dataDitemukan = false;
        while(res.next()){
            dataDitemukan = true;
            String vNik = res.getString("nik");
          //  String vNisn = res.getString("nisn");
            String identitasTampil = res.getString("nik");


            model.addRow(new Object[]{
                res.getString("id_aspirasi"),
                identitasTampil,
                res.getString("nama"),
                res.getString("isi_aspirasi"),
                res.getString("kategori"), 
                res.getString("tanggal"),
                res.getString("status")
                
            });
        }
        tbAspirasi.setModel(model);

        if (!dataDitemukan) {
            System.out.println("Data dengan status " + statusPilihan + " tidak ditemukan di DB.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menyaring status: " + e.getMessage());
    }
}
   
    public void cetakStruk(String idAspirasi) {
    // Tambahkan WHERE id_aspirasi = ? di akhir query
    String sql = "SELECT\n" +
"     aspirasi.`id_aspirasi` AS aspirasi_id_aspirasi,\n" +
"     aspirasi.`nik` AS aspirasi_nik,\n" +
"     aspirasi.`nama` AS aspirasi_nama,\n" +
"     aspirasi.`isi_aspirasi` AS aspirasi_isi_aspirasi,\n" +
"     aspirasi.`status` AS aspirasi_status,\n" +
"     aspirasi.`tanggal` AS aspirasi_tanggal\n" + // Baris feedback/tanggapan dihapus
"FROM\n" +
"     `aspirasi` aspirasi\n" +
"WHERE aspirasi.`id_aspirasi` = ?";
    
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rp = null;
    
    try {
        // Gunakan koneksi yang sudah kamu buat agar konsisten
        connection = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
        
        pst = connection.prepareStatement(sql, 
        ResultSet.TYPE_SCROLL_INSENSITIVE, 
        ResultSet.CONCUR_READ_ONLY);
        pst.setString(1, idAspirasi); // Memasukkan ID ke tanda tanya (?)
        rp = pst.executeQuery();
        
        if (rp.next()) { // Cek apakah data ada
            // Reset ResultSet ke awal sebelum dikirim ke Jasper
            rp.beforeFirst(); 
            
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rp);
            // Pastikan path file .jrxml benar
            JasperReport jasperReport = JasperCompileManager.compileReport("G:\\UKKAspirasi\\src\\ReportUKK\\laporan_id.jrxml");
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);
            
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            viewer.setTitle("Laporan Aspirasi");
            viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(0, 0, screenSize.width, screenSize.height);
            viewer.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan di database.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Cetak: " + e.getMessage());
        e.printStackTrace();
    } finally {
        // Resource closing ditangani agar tidak bocor memory
        try { if (rp != null) rp.close(); } catch (Exception e) {}
        try { if (pst != null) pst.close(); } catch (Exception e) {}
    }
}

   private void bersih() {
    txt_id.setText("");           
    txt_nik.setText("");         
    txt_nama.setText("");         
   
    txt_isi.setText("");          
    cb_status.setSelectedIndex(0); 
    
    // Kunci field teks agar tidak bisa diketik
    txt_id.setEditable(false);
    txt_nik.setEditable(false);
    txt_nama.setEditable(false);
    txt_isi.setEditable(false);
   
}


}
