/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk.admin;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dppra
 */
public class registrasiWaka extends javax.swing.JFrame {

    /**
     * Creates new form registrasi
     */
     //deklarasi variabel conn, rs, dan pst
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    private final DateFormat dfl = new SimpleDateFormat("dd/MM/yyyy");
    Calendar hariIni;
    
    private DefaultTableModel model;
    
    public registrasiWaka() {
        initComponents();
        setLocationRelativeTo(this);// membuat tengah form
        conn = Koneksi.Koneksi.KoneksiDB();
        tampilId();//javaConnect = nama file || Connection = nama method
        this.setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        //memberi penamaan pada judul kolom ; 
        model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("id_petugas");
        model.addColumn("nama");
        model.addColumn("Username");
        model.addColumn("Role");
        getData();//memanggil method getdata
        
    }
void getData() {
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    
    try {
        //membuat statement pemanggilan data pada table surat_masuk dari database 
        String sql = "select * from petugas";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        //penelusuran baris pada table surat_masuk dari database
        while (rs.next()) {
            Object[] obj = new Object[4];
            obj[0] = rs.getString("id_petugas");
            obj[1] = rs.getString("nama");
            obj[2] = rs.getString("username");
            //obj[2] = rs.getString("");
            obj[3] = rs.getString("role");
            model.addRow(obj);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);      
    }
} 
 //menampilkan data dr tabel ke masing-masing komponen cara 2
   void pilihData() {
       int i = jTable1.getSelectedRow();
       txt_username.setText(model.getValueAt(i, 1).toString());
       
   } 
   
   void bersih() {
       txt_id.setText("");
       txt_password.setText("");
       txt_username.setText("");
       txt_nama.setText("");
       cmb_cari.setSelectedItem("");
       
   }
   
   void tampilId() {
    try {
        String sql = "SELECT IFNULL(MAX(id_petugas), 0) + 1 AS id FROM petugas";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();

        if (rs.next()) {
            txt_id.setText(rs.getString("id"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_cari = new javax.swing.JTextField();
        cmb_cari = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmb_role = new javax.swing.JComboBox<>();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrasi Masyarakat");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setBackground(new java.awt.Color(0,0,0,0));
        txt_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_username.setBorder(null);
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 410, 40));

        txt_password.setBackground(new java.awt.Color(0,0,0,0));
        txt_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_password.setBorder(null);
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 410, 40));

        txt_cari.setBackground(new java.awt.Color(0,0,0,0));
        txt_cari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cari.setBorder(null);
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 460, 50));

        cmb_cari.setBackground(new java.awt.Color(0,0,0,0));
        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NAMA" }));
        cmb_cari.setBorder(null);
        cmb_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cariActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 50, 130, 50));

        jButton6.setBackground(new java.awt.Color(0,0,0,0));
        jButton6.setBorder(null);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 50, 110, 50));

        jButton4.setBackground(new java.awt.Color(0,0,0,0));
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 130, 40));

        jButton1.setBackground(new java.awt.Color(0,0,0,0));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 160, 50));

        jButton2.setBackground(new java.awt.Color(0,0,0,0));
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, 150, 40));

        jButton5.setBackground(new java.awt.Color(0,0,0,0));
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 650, 120, 40));

        jButton3.setBackground(new java.awt.Color(0,0,0,0));
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 150, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 730, 520));

        cmb_role.setBackground(new java.awt.Color(0,0,0,0));
        cmb_role.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "waka" }));
        cmb_role.setBorder(null);
        jPanel1.add(cmb_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 400, 40));

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(0,0,0,0));
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_id.setBorder(null);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 400, 40));

        txt_nama.setBackground(new java.awt.Color(0,0,0,0));
        txt_nama.setBorder(null);
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 400, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/registrasi waka.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1365, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

    String id = txt_id.getText();
    String nama = txt_nama.getText();
    String username = txt_username.getText();
    String password = txt_password.getText();
    String role = cmb_role.getSelectedItem().toString();

    String sql = "UPDATE petugas SET nama=?, username=?, password=?, role=? WHERE id_petugas=?";

    pst = conn.prepareStatement(sql);
    pst.setString(1, nama);
    pst.setString(2, username);
    pst.setString(3, password);
    pst.setString(4, role);
    pst.setString(5, id);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Update Berhasil");

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal Update: " + e.getMessage());
}

getData();
bersih();

     
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmb_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cariActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{
           String sql = "insert into petugas (nama, username, password, role)values(?,?,?,?)";
           pst = conn.prepareStatement(sql);
           pst.setString(1, txt_nama.getText());
           pst.setString(2, txt_username.getText());
           pst.setString(3, txt_password.getText());
           pst.setString(4, cmb_role.getSelectedItem().toString());
           pst.execute();
           JOptionPane.showMessageDialog(null, "saved");
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
       }
       getData();
       bersih();
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       bersih();
       getData();
       tampilId();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      int p = JOptionPane.showConfirmDialog(
        null,
        "Apakah benar-benar akan dihapus permanen ?",
        "Delete",
        JOptionPane.YES_NO_OPTION);

if (p == JOptionPane.YES_OPTION) {

    String sql = "DELETE FROM petugas WHERE id_petugas=?";

    try {
        pst = conn.prepareStatement(sql);
        pst.setInt(1, Integer.parseInt(txt_id.getText())); // ✅ pakai id

        int rows = pst.executeUpdate(); // pakai executeUpdate untuk delete

        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    bersih();
    getData();
}
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    ukk.menu.menuAdmin menu = new ukk.menu.menuAdmin();
    
    // 2. Menampilkan Menu Admin
    menu.setVisible(true);
    
    // 3. Menutup halaman Riwayat Aspirasi saat ini
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       String sql = "";
            
         model.getDataVector().removeAllElements();
         model.fireTableDataChanged();
         try {
              if (cmb_cari.getSelectedIndex() == 0) {
                    sql = "SELECT * FROM petugas where id_petugas like '%" + txt_cari.getText() + "%' ";
                    
               }
              if (cmb_cari.getSelectedIndex() == 1) {
                    sql = "SELECT * FROM petugas where nama like '%" + txt_cari.getText() + "%' ";
               }
                
              pst = conn.prepareStatement(sql);
              rs = pst.executeQuery();
                
              while (rs.next()) {
                  Object[] obj = new Object[2];
                  obj[0] = rs.getString("id_petugas");
                  obj[1] = rs.getString("nama");
                  
                  
                    
                    
                  model.addRow(obj);
                }
              
     } catch (Exception e) {
          JOptionPane.showMessageDialog(null, e);
        }       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {

        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow != -1) {

            // Ambil data dari tabel sesuai index kolom
            String id = jTable1.getValueAt(selectedRow, 0).toString();
            String nama = jTable1.getValueAt(selectedRow, 1).toString();
            String username = jTable1.getValueAt(selectedRow, 2).toString();
            String role = jTable1.getValueAt(selectedRow, 3).toString();
            

            // Masukkan ke field
            txt_id.setText(id);
            txt_nama.setText(nama);
            txt_username.setText(username);
            cmb_role.setSelectedItem(role);  // Untuk JComboBox
            

        }
    }
});

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrasiWaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrasiWaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrasiWaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrasiWaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrasiWaka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_cari;
    private javax.swing.JComboBox<String> cmb_role;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
