/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk.admin;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import ukk.menu.menuAdmin;
import java.sql.Connection;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.util.Date;
import java.text.SimpleDateFormat;
import Koneksi.Koneksi;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.TableModel;


/**
 *
 * @author asus
 */
public class TanggapanAdmin extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Koneksi k = new Koneksi();
    String pathFoto = "";
    /**
     * Creates new form TanggapanAdmin
     */
    public TanggapanAdmin() {
        initComponents();
        conn = Koneksi.KoneksiDB();
        tampil_tabel();
        setTanggalHariIni();
        tabel_pengaduan.requestFocus();
        getDataTanggapan();
        this.setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        
    }
    
   public void getDataTanggapan() {
    DefaultTableModel model = (DefaultTableModel) tabel_feedback.getModel();
    model.setRowCount(0);
    try {
        // Ganti INNER JOIN menjadi LEFT JOIN agar data tanggapan tidak hilang
        String sql = "SELECT t.*, p.username FROM tanggapan t "
           + "LEFT JOIN petugas p ON t.id_petugas = p.id_petugas "
           + "ORDER BY t.id_tanggapan DESC"; // Menampilkan data terbaru di atas
        
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        while (rs.next()) {
            // Ambil username, jika null (tidak ketemu) ganti dengan "-"
            String namaPetugas = rs.getString("username");
            if (namaPetugas == null) {
                namaPetugas = "-";
            }

            model.addRow(new Object[]{
                rs.getString("id_tanggapan"),
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("tgl_tang"),
                rs.getString("feedback"),
                rs.getString("status"),
                namaPetugas // Kolom nama petugas dari hasil JOIN
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat tabel bawah: " + e.getMessage());
    }
    }
    
    private void setTanggalHariIni() {
    txt_tgl.setDate(new Date());
    txt_tgl.getDateEditor().setEnabled(false);
    txt_tgl.getCalendarButton().setEnabled(false);
    
    txt_tglpengaduan.setDate(new Date());
    txt_tglpengaduan.getDateEditor().setEnabled(false);
    txt_tglpengaduan.getCalendarButton().setEnabled(false);
}
    private DefaultTableModel model;

    private void bersih() {
    txt_id.setText("");
    txt_NIK.setText("");
    txt_nama.setText("");
    txt_id_petugas.setText("");
    txt_nama_petugas.setText("");
    lokasi.setText("");
    txt_pengaduan.setText("");
    txt_tanggapan.setText("");
    cmb_status.setSelectedIndex(0);
    txt_tgl.setDate(null); 
    lbl_foto.setIcon(null);
//    lbl_foto.setIcon(null);
  //  lbl_foto.setText(""); 
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_NIK = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_tgl = new com.toedter.calendar.JDateChooser();
        cmb_status = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        cmb_kategori = new javax.swing.JComboBox<>();
        btn_cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pengaduan = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_feedback = new javax.swing.JTable();
        txt_id = new javax.swing.JTextField();
        btn_refrest = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_pengaduan = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_tanggapan = new javax.swing.JTextArea();
        detail = new javax.swing.JButton();
        lbl_foto = new javax.swing.JLabel();
        txt_tglpengaduan = new com.toedter.calendar.JDateChooser();
        cb_kategori = new javax.swing.JComboBox<>();
        lokasi = new javax.swing.JTextField();
        txt_id_petugas = new javax.swing.JTextField();
        btn_cek_petugas = new javax.swing.JButton();
        txt_nama_petugas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_NIK.setBackground(new java.awt.Color(0,0,0,0));
        txt_NIK.setBorder(null);
        txt_NIK.setEnabled(false);
        getContentPane().add(txt_NIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 360, 30));

        txt_nama.setBackground(new java.awt.Color(0,0,0,0));
        txt_nama.setBorder(null);
        txt_nama.setEnabled(false);
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 360, 30));

        txt_tgl.setEnabled(false);
        getContentPane().add(txt_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 360, 30));

        cmb_status.setBackground(new java.awt.Color(0,0,0,0));
        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "terverifikasi", "tertanggapi" }));
        cmb_status.setBorder(null);
        cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_statusActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 360, 30));

        jButton1.setBackground(new java.awt.Color(0,0,0,0));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 140, 50));

        jButton3.setBackground(new java.awt.Color(0,0,0,0));
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 640, 110, 50));

        txt_cari.setBackground(new java.awt.Color(0,0,0,0));
        txt_cari.setBorder(null);
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 410, 40));

        cmb_kategori.setBackground(new java.awt.Color(0,0,0,0));
        cmb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIK", "Nama" }));
        getContentPane().add(cmb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 70, 110, 40));

        btn_cari.setBackground(new java.awt.Color(0,0,0,0));
        btn_cari.setBorder(null);
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 70, 130, 40));

        tabel_pengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NIK/NISN", "Nama", "Tanggal", "Pengaduan", "Kategori", "Foto", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_pengaduan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pengaduanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pengaduan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 710, 140));

        tabel_feedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NK/NISN", "Nama", "Tanggal", "Feedback", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_feedbackMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabel_feedback);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 700, 140));

        txt_id.setBackground(new java.awt.Color(0,0,0,0));
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id.setBorder(null);
        txt_id.setEnabled(false);
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 360, 30));

        btn_refrest.setBackground(new java.awt.Color(0,0,0,0));
        btn_refrest.setBorder(null);
        btn_refrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refrestActionPerformed(evt);
            }
        });
        getContentPane().add(btn_refrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 640, 140, 50));

        txt_pengaduan.setBackground(new java.awt.Color(0,0,0,0));
        txt_pengaduan.setColumns(20);
        txt_pengaduan.setRows(5);
        txt_pengaduan.setEnabled(false);
        jScrollPane2.setViewportView(txt_pengaduan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 360, 60));

        txt_tanggapan.setBackground(new java.awt.Color(0,0,0,0));
        txt_tanggapan.setColumns(20);
        txt_tanggapan.setRows(5);
        txt_tanggapan.setBorder(null);
        jScrollPane3.setViewportView(txt_tanggapan);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 360, 60));

        detail.setBackground(new java.awt.Color(0,0,0,0));
        detail.setBorder(null);
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });
        getContentPane().add(detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, 140, 50));

        lbl_foto.setBackground(new java.awt.Color(0,0,0,0));
        getContentPane().add(lbl_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 140, 180));
        getContentPane().add(txt_tglpengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 360, 30));

        cb_kategori.setBackground(new java.awt.Color(0,0,0,0));
        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sarana", "prasarana" }));
        cb_kategori.setBorder(null);
        getContentPane().add(cb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 360, 30));

        lokasi.setBackground(new java.awt.Color(0,0,0,0));
        lokasi.setBorder(null);
        lokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokasiActionPerformed(evt);
            }
        });
        getContentPane().add(lokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 360, 30));

        txt_id_petugas.setBackground(new java.awt.Color(0,0,0,0));
        txt_id_petugas.setBorder(null);
        getContentPane().add(txt_id_petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 360, 30));

        btn_cek_petugas.setBackground(new java.awt.Color(0,0,0,0));
        btn_cek_petugas.setBorder(null);
        btn_cek_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cek_petugasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cek_petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 40, 30));

        txt_nama_petugas.setBackground(new java.awt.Color(0,0,0,0));
        txt_nama_petugas.setEnabled(false);
        getContentPane().add(txt_nama_petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 360, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ukk/admin/tanggapan pengaduan (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void tampil_tabel() {
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    model.addColumn("ID");
    model.addColumn("NIK/NISN");
    model.addColumn("Nama");
    model.addColumn("Tanggal");
    model.addColumn("Pengaduan");
    model.addColumn("Kategori");
    model.addColumn("Lokasi");
    model.addColumn("Foto");
    model.addColumn("Status");
    
   // model.addColumn("Feedback");

    try {
        String sql = "SELECT id_pengaduan, nik, nama, tgl_pengaduan, isi_laporan, kategori, lokasi, foto, status "
                   + "FROM pengaduan "
                   + "WHERE status = 'Terverifikasi'";

        java.sql.Connection conn = k.KoneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_pengaduan"),
                res.getString("nik"),
                res.getString("nama"),
                res.getString("tgl_pengaduan"),
                res.getString("isi_laporan"),
                res.getString("kategori"),
                res.getString("lokasi"),
                res.getString("foto"),
                res.getString("status"),
                //res.getString("feedback")
            });
        }

        tabel_pengaduan.setModel(model);

    } catch (Exception e) {
        System.out.println("Error tampil data: " + e.getMessage());
    }
}   
    
    
    //tampil table tanggapan
    public void tampil_tabel1() {
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    model.addColumn("ID");
    model.addColumn("ID_Pengaduan");
    model.addColumn("NIK/NISN");
    model.addColumn("Nama");
    model.addColumn("Tanggal");
    model.addColumn("Pengaduan");
    model.addColumn("Kategori");
    model.addColumn("Foto");
    model.addColumn("Status");

    try {
        String sql = "SELECT id_pengaduan, nik, nama, tgl_pengaduan, isi_laporan, kategori, foto, status "
                   + "FROM pengaduan "
                   + "WHERE status = 'Tertanggapi'";

        java.sql.Connection conn = k.KoneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_tanggapan"),
                res.getString("id_pengaduan"),
                res.getString("nik"),
                res.getString("nama"),
                res.getString("tgl_pengaduan"),
                res.getString("isi_laporan"),
                res.getString("kategori"),
                res.getString("foto"),
                res.getString("status")
            });
        }

        tabel_feedback.setModel(model);

    } catch (Exception e) {
        System.out.println("Error tampil data: " + e.getMessage());
    }
}

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_statusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda ingin kembali ke Menu Utama?", 
            "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        new menuAdmin().setVisible(true); 
        
        this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 // 1. Validasi Input: Pastikan ID dan Tanggapan (feedback) tidak kosong
// 1. Validasi Input Tetap Sama
if (txt_id.getText().isEmpty() || txt_NIK.getText().isEmpty() || 
        txt_nama.getText().isEmpty() || txt_pengaduan.getText().isEmpty() || 
        txt_tanggapan.getText().isEmpty() || txt_id_petugas.getText().isEmpty()) {
        
        JOptionPane.showMessageDialog(null, "Semua kolom termasuk ID Petugas wajib diisi!");
        return;
    }

    try {
        // 2. PENGATURAN TANGGAL: Mengambil data dari JDateChooser
        String format = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(format);
        String tanggalPengaduan = fm.format(txt_tgl.getDate());
        String tanggalTanggapan = fm.format(txt_tglpengaduan.getDate());
        
        // 3. AMBIL DATA DARI KOMPONEN GUI
        String statusTerpilih = cmb_status.getSelectedItem().toString();
        Connection conn = k.KoneksiDB();

        // 4. BAGIAN 1: SIMPAN KE TABEL TANGGAPAN (DATABASE ukk_net)
        String sqlSimpan = "INSERT INTO tanggapan "
                + "(id_pengaduan, nik, nama, tanggal, tgl_tang, "
                + "isi_pengaduan, kategori, lokasi, status, feedback, foto, id_petugas, nama_petugas) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement pst = conn.prepareStatement(sqlSimpan);
        pst.setString(1, txt_id.getText());
        pst.setString(2, txt_NIK.getText());
        pst.setString(3, txt_nama.getText());
        pst.setString(4, tanggalPengaduan);
        pst.setString(5, tanggalTanggapan);
        pst.setString(6, txt_pengaduan.getText());
        pst.setString(7, cb_kategori.getSelectedItem().toString());
        pst.setString(8, lokasi.getText());
        pst.setString(9, statusTerpilih);
        pst.setString(10, txt_tanggapan.getText());
        pst.setString(11, (pathFoto == null) ? "" : pathFoto);
        
        // Menggunakan setString agar tidak error tipe data saat mengambil dari JTextField
        pst.setString(12, txt_id_petugas.getText()); 
        pst.setString(13, txt_nama_petugas.getText()); 

        pst.executeUpdate(); // Eksekusi simpan pertama

        // 5. BAGIAN 2: UPDATE OTOMATIS STATUS DI TABEL PENGADUAN
        String sqlUpdateStatus = "UPDATE pengaduan SET status = ? WHERE id_pengaduan = ?";
        PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdateStatus);
        pstUpdate.setString(1, statusTerpilih);
        pstUpdate.setString(2, txt_id.getText()); 
        pstUpdate.executeUpdate(); // Eksekusi update kedua

        // 6. BAGIAN 3: PENYELESAIAN DAN REFRESH DATA
        JOptionPane.showMessageDialog(null, "Tanggapan berhasil disimpan dan status diperbarui!");

        tampil_tabel();       // Refresh tabel daftar pengaduan (atas)
        getDataTanggapan();   // Refresh tabel riwayat tanggapan (bawah)
        bersih();             // Kosongkan form input agar siap dipakai lagi

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Simpan: " + e.getMessage());
        e.printStackTrace();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
    String kategori = cmb_kategori.getSelectedItem().toString();
    String keyword = txt_cari.getText(); 

    if (keyword.equals("")) {
        JOptionPane.showMessageDialog(null, "Masukkan " + kategori + " yang ingin dicari!");
        tampil_tabel(); 
    } else {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NIK/NISN");
        model.addColumn("Nama");
        model.addColumn("Tanggal");
        model.addColumn("Pengaduan");
        model.addColumn("Kategori");
        model.addColumn("Foto");
        model.addColumn("Status");

        try {
            java.sql.Connection conn = k.KoneksiDB();
            String sql = "";

            if (kategori.equals("NIK")) {
            sql = "SELECT * FROM pengaduan "
                + "WHERE nik LIKE ? AND status = 'Terverifikasi'";
        } else {
            sql = "SELECT * FROM pengaduan "
                + "WHERE nama LIKE ? AND status = 'Terverifikasi'";
        }

            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + keyword + "%");
            java.sql.ResultSet res = pst.executeQuery();

            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("id_pengaduan"),
                    res.getString("nik"), 
                    res.getString("nama"),
                    res.getString("tgl_pengaduan"),
                    res.getString("isi_laporan"),
                    res.getString("kategori"),
                    res.getString("foto"),
                    res.getString("status")
                });
            }
            tabel_pengaduan.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pencarian Gagal: Kolom database tidak ditemukan.");
            System.out.println(e.getMessage());
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cariActionPerformed

    private void tabel_pengaduanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pengaduanMouseClicked
    tabel_feedback.clearSelection();                                            
    int baris = tabel_pengaduan.getSelectedRow();
    if (baris == -1) return;

    try {

        // ================= FIELD TEXT =================
        txt_id.setText(tabel_pengaduan.getValueAt(baris, 0).toString());
        txt_NIK.setText(tabel_pengaduan.getValueAt(baris, 1).toString());
        txt_nama.setText(tabel_pengaduan.getValueAt(baris, 2).toString());
        txt_pengaduan.setText(tabel_pengaduan.getValueAt(baris, 4).toString());
        lokasi.setText(tabel_pengaduan.getValueAt(baris, 6).toString());

        // ================= TANGGAL =================
        String tanggal = tabel_pengaduan.getValueAt(baris, 3).toString();
        java.util.Date date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggal);
        txt_tgl.setDate(date);
        
        // ================= STATUS =================
        String kategori = tabel_pengaduan.getValueAt(baris, 5).toString();
        cb_kategori.setSelectedItem(kategori);
        // ================= STATUS =================
        String status = tabel_pengaduan.getValueAt(baris, 8).toString();
        cmb_status.setSelectedItem(status);

        // ================= FOTO =================
        String foto = tabel_pengaduan.getValueAt(baris, 7).toString();
        
        this.pathFoto = foto;

        if (foto != null && !foto.equals("")) {

            File file = new File(foto); // karena di tabel sudah full path (C:\Users\...)
            
            if (file.exists()) {
                ImageIcon icon = new ImageIcon(file.getAbsolutePath());
                Image img = icon.getImage().getScaledInstance(
                        lbl_foto.getWidth(),
                        lbl_foto.getHeight(),
                        Image.SCALE_SMOOTH);

                lbl_foto.setIcon(new ImageIcon(img));
            } else {
                lbl_foto.setIcon(null);
            }

        } else {
            lbl_foto.setIcon(null);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal ambil data: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_pengaduanMouseClicked

    private void btn_refrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refrestActionPerformed
    txt_cari.setText(""); 
    tampil_tabel();
    txt_id_petugas.setText("");
    getDataTanggapan();
    bersih();   
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_refrestActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
    int rowAtas = tabel_pengaduan.getSelectedRow();
    int rowBawah = tabel_feedback.getSelectedRow();

    if (rowAtas == -1 && rowBawah == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dari salah satu tabel terlebih dahulu!");
        return;
    }

    // Inisialisasi variabel
    String id="", nik="", nama="", tgl="", isi="", kat="", lok="", foto="", stat="", feedback="", petugas="";
    String teksTampilan = "";

    try {
        java.sql.Connection conn = Koneksi.KoneksiDB(); //

        if (rowAtas != -1) {
            // --- TABEL ATAS (PENGADUAN) ---
            id   = tabel_pengaduan.getValueAt(rowAtas, 0).toString();
            nik  = tabel_pengaduan.getValueAt(rowAtas, 1).toString();
            nama = tabel_pengaduan.getValueAt(rowAtas, 2).toString();
            tgl  = tabel_pengaduan.getValueAt(rowAtas, 3).toString();
            isi  = tabel_pengaduan.getValueAt(rowAtas, 4).toString(); // Kolom Pengaduan
            kat  = tabel_pengaduan.getValueAt(rowAtas, 5).toString(); // Kolom Kategori
            lok  = tabel_pengaduan.getValueAt(rowAtas, 6).toString(); // Kolom Lokasi
            foto = tabel_pengaduan.getValueAt(rowAtas, 7).toString(); // Kolom Foto
            stat = tabel_pengaduan.getValueAt(rowAtas, 8).toString(); // Kolom Status

            teksTampilan = 
                "ID           : " + id + "\n" +
                "NIK/NISN     : " + nik + "\n" +
                "Nama Pelapor : " + nama + "\n" +
                "Tanggal      : " + tgl + "\n" +
                "Kategori     : " + kat + "\n" +
                "Lokasi       : " + lok + "\n" +
                "Status       : " + stat + "\n\n" +
                "Isi Laporan  :\n" + isi;

        } else {
            // --- TABEL BAWAH (TANGGAPAN) ---
            id       = tabel_feedback.getValueAt(rowBawah, 0).toString();
            nik      = tabel_feedback.getValueAt(rowBawah, 1).toString();
            nama     = tabel_feedback.getValueAt(rowBawah, 2).toString();
            tgl      = tabel_feedback.getValueAt(rowBawah, 3).toString();
            feedback = tabel_feedback.getValueAt(rowBawah, 4).toString();
            stat     = tabel_feedback.getValueAt(rowBawah, 5).toString();
            
            // Query ambil Username, Foto, Kategori, Lokasi, dan Isi dari DB
            String sql = "SELECT p.username, peng.foto, peng.isi_laporan, peng.kategori, peng.lokasi "
                       + "FROM tanggapan t "
                       + "JOIN petugas p ON t.id_petugas = p.id_petugas "
                       + "JOIN pengaduan peng ON t.id_pengaduan = peng.id_pengaduan "
                       + "WHERE t.id_tanggapan = '" + id + "'";
            
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            if (rs.next()) {
                petugas = rs.getString("username"); //
                foto    = rs.getString("foto");     
                isi     = rs.getString("isi_laporan");
                kat     = rs.getString("kategori");
                lok     = rs.getString("lokasi");
            }

            teksTampilan = 
                "ID           : " + id + "\n" +
                "NIK/NISN     : " + nik + "\n" +
                "Nama Pelapor : " + nama + "\n" +
                "Nama Petugas : " + petugas + "\n" +
                "Tanggal      : " + tgl + "\n" +
                "Status       : " + stat + "\n\n" +
                "Isi Laporan Asli :\n" + isi +"\n\n" +
                "Feedback/Tanggapan :\n" + feedback;
        }

        // --- SETUP TAMPILAN ---
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        JTextArea txt = new JTextArea(teksTampilan);
        txt.setEditable(false);
        txt.setLineWrap(true);
        txt.setWrapStyleWord(true);
        txt.setFont(new java.awt.Font("Monospaced", 0, 12)); 
        
        JScrollPane scroll = new JScrollPane(txt);
        scroll.setPreferredSize(new Dimension(450, 400));
        panel.add(scroll, BorderLayout.CENTER);

        if (foto != null && !foto.isEmpty() && !foto.equals("-")) {
            try {
                JLabel lblFoto = new JLabel();
                ImageIcon icon = new ImageIcon(foto);
                Image img = icon.getImage().getScaledInstance(250, 300, Image.SCALE_SMOOTH);
                lblFoto.setIcon(new ImageIcon(img));
                panel.add(lblFoto, BorderLayout.EAST);
            } catch (Exception e) {}
        }

        JOptionPane.showMessageDialog(this, panel, "Detail", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Kesalahan: " + e.getMessage());
    }
    
    tabel_pengaduan.clearSelection();
    tabel_feedback.clearSelection();
            // TODO add your handling code here:
    }//GEN-LAST:event_detailActionPerformed

    private void lokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lokasiActionPerformed

    private void btn_cek_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cek_petugasActionPerformed
    try {
        String sql = "SELECT username FROM petugas WHERE id_petugas = ?";
        pst = conn.prepareStatement(sql);
        pst.setString(1, txt_id_petugas.getText());
        rs = pst.executeQuery();
        
        if (rs.next()) {
            // Jika ID ketemu, tampilkan namanya di field kedua
            txt_nama_petugas.setText(rs.getString("username"));
        } else {
            // Jika tidak ada, kosongkan dan beri peringatan
            txt_nama_petugas.setText("");
            JOptionPane.showMessageDialog(null, "ID Petugas tidak ditemukan!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal mengecek petugas: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cek_petugasActionPerformed

    private void tabel_feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_feedbackMouseClicked
        tabel_pengaduan.clearSelection();
    int baris = tabel_pengaduan.getSelectedRow();
    if (baris == -1) return; // kalau belum pilih baris

    try {

        // ================= BASIC DATA =================
        txt_id.setText(
            tabel_pengaduan.getValueAt(baris, 0) != null ?
            tabel_pengaduan.getValueAt(baris, 0).toString() : ""
        );

        txt_NIK.setText(
            tabel_pengaduan.getValueAt(baris, 1) != null ?
            tabel_pengaduan.getValueAt(baris, 1).toString() : ""
        );

        txt_nama.setText(
            tabel_pengaduan.getValueAt(baris, 2) != null ?
            tabel_pengaduan.getValueAt(baris, 2).toString() : ""
        );

        txt_pengaduan.setText(
            tabel_pengaduan.getValueAt(baris, 4) != null ?
            tabel_pengaduan.getValueAt(baris, 4).toString() : ""
        );

        // ================= TANGGAL =================
        if (tabel_pengaduan.getValueAt(baris, 3) != null) {
            String s = tabel_pengaduan.getValueAt(baris, 3).toString();
            java.util.Date date =
                new java.text.SimpleDateFormat("yyyy-MM-dd").parse(s);
            txt_tgl.setDate(date);
        } else {
            txt_tgl.setDate(null);
        }

        // ================= STATUS =================
        if (tabel_pengaduan.getValueAt(baris, 7) != null) {
            String status_tabel =
                tabel_pengaduan.getValueAt(baris, 7).toString();
            cmb_status.setSelectedItem(status_tabel);
        }

        // ================= FOTO =================
        if (tabel_pengaduan.getValueAt(baris, 6) != null) {
            String foto =
                tabel_pengaduan.getValueAt(baris, 6).toString();

            if (!foto.equals("")) {
                ImageIcon icon = new ImageIcon(foto);
                Image img = icon.getImage().getScaledInstance(
                        lbl_foto.getWidth(),
                        lbl_foto.getHeight(),
                        Image.SCALE_SMOOTH
                );
                lbl_foto.setIcon(new ImageIcon(img));
            } else {
                lbl_foto.setIcon(null);
            }
        } else {
            lbl_foto.setIcon(null);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,
            "Gagal mengambil data tabel: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_feedbackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TanggapanAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_cek_petugas;
    private javax.swing.JButton btn_refrest;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JComboBox<String> cmb_kategori;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JButton detail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JTextField lokasi;
    private javax.swing.JTable tabel_feedback;
    private javax.swing.JTable tabel_pengaduan;
    private javax.swing.JTextField txt_NIK;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id_petugas;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nama_petugas;
    private javax.swing.JTextArea txt_pengaduan;
    private javax.swing.JTextArea txt_tanggapan;
    private com.toedter.calendar.JDateChooser txt_tgl;
    private com.toedter.calendar.JDateChooser txt_tglpengaduan;
    // End of variables declaration//GEN-END:variables

}
