/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk.admin;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import ukk.menu.menuAdmin;
import java.sql.Connection;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.util.Date;
import java.text.SimpleDateFormat;
import Koneksi.Koneksi;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.TableModel;

/**
 *
 * @author asus
 */
public class TanggapanAdmin extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Koneksi k = new Koneksi();
    String pathFoto = null;
    /**
     * Creates new form TanggapanAdmin
     */
    public TanggapanAdmin() {
        initComponents();
        tampil_tabel();
        conn = Koneksi.KoneksiDB();
        setTanggalHariIni();
        tabel_pengaduan.requestFocus();
        
        
    }
    
    
    private void setTanggalHariIni() {
    txt_tgl.setDate(new Date());
    txt_tgl.getDateEditor().setEnabled(false);
    txt_tgl.getCalendarButton().setEnabled(false);
    
    txt_tglpengaduan.setDate(new Date());
    txt_tglpengaduan.getDateEditor().setEnabled(false);
    txt_tglpengaduan.getCalendarButton().setEnabled(false);
}
    private DefaultTableModel model;
//    public void tampil_gambar(String nama_foto) {
//    try {
//        java.io.File file = new java.io.File(nama_foto); 
//        if (file.exists()) {
//            ImageIcon icon = new ImageIcon(file.getAbsolutePath());
//            Image img = icon.getImage().getScaledInstance(lbl_foto.getWidth(), lbl_foto.getHeight(), Image.SCALE_SMOOTH);
//            lbl_foto.setIcon(new ImageIcon(img));
//            lbl_foto.setText(""); 
//        } else {
//            lbl_foto.setIcon(null);
//            lbl_foto.setText("File Tidak Ditemukan");
//        }
//    } catch (Exception e) {
//        System.err.println(e.getMessage());
//    }
//}
    private void bersih() {
    txt_id.setText("");
    txt_NIK.setText("");
    txt_nama.setText("");
    txt_pengaduan.setText("");
    txt_tanggapan.setText("");
    cmb_status.setSelectedIndex(0);
    txt_tgl.setDate(null); 
//    lbl_foto.setIcon(null);
  //  lbl_foto.setText(""); 
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_NIK = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_tgl = new com.toedter.calendar.JDateChooser();
        cmb_status = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        cmb_kategori = new javax.swing.JComboBox<>();
        btn_cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pengaduan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_refrest = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_pengaduan = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_tanggapan = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        detail = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_tanggapan = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_tglpengaduan = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        cb_kategori = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lokasi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Tanggapan Admin");

        txt_NIK.setEnabled(false);

        txt_nama.setEnabled(false);
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_tgl.setEnabled(false);

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "terverifikasi", "tertanggapi" }));
        cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_statusActionPerformed(evt);
            }
        });

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cetak");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });

        cmb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIK", "Nama" }));

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        tabel_pengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NIK/NISN", "Nama", "Tanggal", "Pengaduan", "Kategori", "Foto", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_pengaduan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pengaduanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pengaduan);

        jLabel3.setText("NIK");

        jLabel4.setText("Nama");

        jLabel5.setText("Tanggal pengaduan");

        jLabel6.setText("Status");

        jLabel7.setText("Isi Pengaduan");

        txt_id.setEnabled(false);

        jLabel9.setText("ID");

        btn_refrest.setText("Refrest");
        btn_refrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refrestActionPerformed(evt);
            }
        });

        txt_pengaduan.setColumns(20);
        txt_pengaduan.setRows(5);
        txt_pengaduan.setEnabled(false);
        jScrollPane2.setViewportView(txt_pengaduan);

        txt_tanggapan.setColumns(20);
        txt_tanggapan.setRows(5);
        jScrollPane3.setViewportView(txt_tanggapan);

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        detail.setText("detail");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });

        jLabel2.setText("Feedback");

        tabel_tanggapan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_tanggapan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_tanggapanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabel_tanggapan);

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Tanggal tanggapan");

        jLabel11.setText("Foto");

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sarana", "prasarana" }));

        jLabel12.setText("Kategori");

        jLabel13.setText("Lokasi");

        lokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel5))
                                                .addGap(13, 13, 13))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                            .addComponent(cmb_status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_nama)
                                            .addComponent(txt_id)
                                            .addComponent(txt_NIK)
                                            .addComponent(jScrollPane2)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lokasi)
                                            .addComponent(cb_kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_tglpengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_refrest))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_cari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cari)
                            .addComponent(btn_refrest)
                            .addComponent(cmb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_NIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txt_tglpengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(detail)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public void tampil_tabel() {
//    DefaultTableModel model = new DefaultTableModel() {
//        @Override
//        public boolean isCellEditable(int row, int column) {
//            return false; 
//        }
//    };
//    
//    model.addColumn("ID");
//    model.addColumn("NIK/NISN");
//    model.addColumn("Nama");
//    model.addColumn("Tanggal");
//    model.addColumn("Pengaduan");
//    model.addColumn("Kategori");
//    model.addColumn("Foto");
//    model.addColumn("Status");
//    model.addColumn("feedback");
//
//    try {
//        String sql = "SELECT id_pengaduan, nik, nama, tgl_pengaduan, isi_laporan, kategori, foto, status FROM pengaduan";
//        java.sql.Connection conn = k.KoneksiDB();
//        java.sql.Statement stm = conn.createStatement();
//        java.sql.ResultSet res = stm.executeQuery(sql);
//
//        while (res.next()) {
//            model.addRow(new Object[]{
//                res.getString("id_pengaduan"),
//                res.getString("nik"),
//                res.getString("nama"),
//                res.getString("tgl_pengaduan"),
//                res.getString("isi_laporan"),
//                res.getString("kategori"),
//                res.getString("foto"),
//                res.getString("status")
//            });
//        }
//        
//        tabel_pengaduan.setModel(model); 
//        
//    } catch (Exception e) {
//        System.out.println("Error tampil data: " + e.getMessage());
//    }
//}
    
    public void tampil_tabel() {
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    model.addColumn("ID");
    model.addColumn("NIK/NISN");
    model.addColumn("Nama");
    model.addColumn("Tanggal");
    model.addColumn("Pengaduan");
    model.addColumn("Kategori");
    model.addColumn("Lokasi");
    model.addColumn("Foto");
    model.addColumn("Status");
    
   // model.addColumn("Feedback");

    try {
        String sql = "SELECT id_pengaduan, nik, nama, tgl_pengaduan, isi_laporan, kategori, lokasi, foto, status "
                   + "FROM pengaduan "
                   + "WHERE status = 'Terverifikasi'";

        java.sql.Connection conn = k.KoneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_pengaduan"),
                res.getString("nik"),
                res.getString("nama"),
                res.getString("tgl_pengaduan"),
                res.getString("isi_laporan"),
                res.getString("kategori"),
                res.getString("lokasi"),
                res.getString("foto"),
                res.getString("status"),
                //res.getString("feedback")
            });
        }

        tabel_pengaduan.setModel(model);

    } catch (Exception e) {
        System.out.println("Error tampil data: " + e.getMessage());
    }
}   
    
    
    //tampil table tanggapan
    public void tampil_tabel1() {
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    model.addColumn("ID");
    model.addColumn("ID_Pengaduan");
    model.addColumn("NIK/NISN");
    model.addColumn("Nama");
    model.addColumn("Tanggal");
    model.addColumn("Pengaduan");
    model.addColumn("Kategori");
    model.addColumn("Foto");
    model.addColumn("Status");

    try {
        String sql = "SELECT id_pengaduan, nik, nama, tgl_pengaduan, isi_laporan, kategori, foto, status "
                   + "FROM pengaduan "
                   + "WHERE status = 'Tertanggapi'";

        java.sql.Connection conn = k.KoneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_tanggapan"),
                res.getString("id_pengaduan"),
                res.getString("nik"),
                res.getString("nama"),
                res.getString("tgl_pengaduan"),
                res.getString("isi_laporan"),
                res.getString("kategori"),
                res.getString("foto"),
                res.getString("status")
            });
        }

        tabel_tanggapan.setModel(model);

    } catch (Exception e) {
        System.out.println("Error tampil data: " + e.getMessage());
    }
}

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_statusActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                         
    int baris = tabel_pengaduan.getSelectedRow();
    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data di tabel yang ingin dicetak!");
        return;
    }

    // Ambil ID dari kolom ke-0 (id_pengaduan)
    String idTerpilih = tabel_pengaduan.getValueAt(baris, 0).toString();

    try {
        // 1. Lokasi file report (.jasper)
        String reportPath = "src/ukk/ReportUKK/laporan_pengaduan.jasper";
        
        // 2. Menyiapkan Parameter
        HashMap<String, Object> parameters = new HashMap<>();
        parameters.put("id_pengaduan", idTerpilih); // Nama parameter harus sama dengan di Jasper

        // 3. Koneksi Database (Gunakan class koneksi kamu)
        Connection conn = k.KoneksiDB(); 

        // 4. Proses Cetak
        JasperPrint jp = JasperFillManager.fillReport(reportPath, parameters, conn);
        JasperViewer.viewReport(jp, false); // 'false' agar aplikasi utama tidak tertutup saat report disilang

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mencetak: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda ingin kembali ke Menu Utama?", 
            "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        new menuAdmin().setVisible(true); 
        
        this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 // 1. Validasi Input: Pastikan ID dan Tanggapan (feedback) tidak kosong
// 1. Validasi Input Tetap Sama
if (txt_id.getText().isEmpty() || txt_NIK.getText().isEmpty() || 
    txt_nama.getText().isEmpty() || txt_pengaduan.getText().isEmpty() || 
    txt_tanggapan.getText().isEmpty()) {
    
    JOptionPane.showMessageDialog(null, "Semua kolom wajib diisi!");
    return;
}

try {
    String format = "yyyy-MM-dd";
    SimpleDateFormat fm = new SimpleDateFormat(format);

    String tanggalPengaduan = fm.format(txt_tgl.getDate());
    String tanggalTanggapan = fm.format(txt_tglpengaduan.getDate());
    
    // Ambil status dari ComboBox
    String statusTerpilih = cmb_status.getSelectedItem().toString();

    Connection conn = k.KoneksiDB();

    // --- BAGIAN 1: INSERT KE TABEL TANGGAPAN (RIWAYAT) ---
    String sqlSimpan = "INSERT INTO tanggapan "
            + "(id_pengaduan, nik, nama, tanggal, tgl_tang, "
            + "isi_pengaduan, kategori, lokasi, status, feedback, foto) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    PreparedStatement pst = conn.prepareStatement(sqlSimpan);
    pst.setString(1, txt_id.getText());
    pst.setString(2, txt_NIK.getText());
    pst.setString(3, txt_nama.getText());
    pst.setString(4, tanggalPengaduan);
    pst.setString(5, tanggalTanggapan);
    pst.setString(6, txt_pengaduan.getText());
    pst.setString(7, cb_kategori.getSelectedItem().toString());
    pst.setString(8, lokasi.getText());
    pst.setString(9, statusTerpilih);
    pst.setString(10, txt_tanggapan.getText());
    pst.setString(11, (pathFoto == null) ? "" : pathFoto);

    pst.executeUpdate();

    // --- BAGIAN 2: UPDATE OTOMATIS STATUS DI TABEL PENGADUAN ---
    // Logika: Jika admin memilih status "Selesai" atau "Tertanggapi", 
    // maka tabel sumber (pengaduan) juga harus update statusnya.
    
    String sqlUpdateStatus = "UPDATE pengaduan SET status = ? WHERE id_pengaduan = ?";
    PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdateStatus);
    pstUpdate.setString(1, statusTerpilih);
    pstUpdate.setString(2, txt_id.getText()); // Menggunakan ID yang sama
    pstUpdate.executeUpdate();

    JOptionPane.showMessageDialog(null, "Tanggapan berhasil disimpan dan status diperbarui!");

    tampil_tabel();
    bersih();

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    e.printStackTrace();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
    String kategori = cmb_kategori.getSelectedItem().toString();
    String keyword = txt_cari.getText(); 

    if (keyword.equals("")) {
        JOptionPane.showMessageDialog(null, "Masukkan " + kategori + " yang ingin dicari!");
        tampil_tabel(); 
    } else {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NIK/NISN");
        model.addColumn("Nama");
        model.addColumn("Tanggal");
        model.addColumn("Pengaduan");
        model.addColumn("Kategori");
        model.addColumn("Foto");
        model.addColumn("Status");

        try {
            java.sql.Connection conn = k.KoneksiDB();
            String sql = "";

            if (kategori.equals("NIK")) {
            sql = "SELECT * FROM pengaduan "
                + "WHERE nik LIKE ? AND status = 'Terverifikasi'";
        } else {
            sql = "SELECT * FROM pengaduan "
                + "WHERE nama LIKE ? AND status = 'Terverifikasi'";
        }

            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + keyword + "%");
            java.sql.ResultSet res = pst.executeQuery();

            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("id_pengaduan"),
                    res.getString("nik"), 
                    res.getString("nama"),
                    res.getString("tgl_pengaduan"),
                    res.getString("isi_laporan"),
                    res.getString("kategori"),
                    res.getString("foto"),
                    res.getString("status")
                });
            }
            tabel_pengaduan.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pencarian Gagal: Kolom database tidak ditemukan.");
            System.out.println(e.getMessage());
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cariActionPerformed

    private void tabel_pengaduanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pengaduanMouseClicked
                                            
    int baris = tabel_pengaduan.getSelectedRow();
    if (baris == -1) return;

    try {

        // ================= FIELD TEXT =================
        txt_id.setText(tabel_pengaduan.getValueAt(baris, 0).toString());
        txt_NIK.setText(tabel_pengaduan.getValueAt(baris, 1).toString());
        txt_nama.setText(tabel_pengaduan.getValueAt(baris, 2).toString());
        txt_pengaduan.setText(tabel_pengaduan.getValueAt(baris, 4).toString());
        lokasi.setText(tabel_pengaduan.getValueAt(baris, 6).toString());

        // ================= TANGGAL =================
        String tanggal = tabel_pengaduan.getValueAt(baris, 3).toString();
        java.util.Date date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggal);
        txt_tgl.setDate(date);
        
        // ================= STATUS =================
        String kategori = tabel_pengaduan.getValueAt(baris, 5).toString();
        cb_kategori.setSelectedItem(kategori);
        // ================= STATUS =================
        String status = tabel_pengaduan.getValueAt(baris, 8).toString();
        cmb_status.setSelectedItem(status);

        // ================= FOTO =================
        String foto = tabel_pengaduan.getValueAt(baris, 7).toString();

        if (foto != null && !foto.equals("")) {

            File file = new File(foto); // karena di tabel sudah full path (C:\Users\...)
            
            if (file.exists()) {
                ImageIcon icon = new ImageIcon(file.getAbsolutePath());
                Image img = icon.getImage().getScaledInstance(
                        jLabel8.getWidth(),
                        jLabel8.getHeight(),
                        Image.SCALE_SMOOTH);

                jLabel8.setIcon(new ImageIcon(img));
            } else {
                jLabel8.setIcon(null);
            }

        } else {
            jLabel8.setIcon(null);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal ambil data: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_pengaduanMouseClicked

    private void btn_refrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refrestActionPerformed
    txt_cari.setText(""); 
    tampil_tabel(); 
    bersih();   
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_refrestActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if (txt_id.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Gagal Update: Pilih data di tabel terlebih dahulu!");
    } else {
    try {
        java.sql.Connection conn = k.KoneksiDB();

        String sqlTanggapan = "UPDATE tanggapan SET tanggapan = ? WHERE id_pengaduan = ?";
        java.sql.PreparedStatement pst1 = conn.prepareStatement(sqlTanggapan);
        pst1.setString(1, txt_tanggapan.getText());
        pst1.setString(2, txt_id.getText());
        pst1.execute();

        String sqlStatus = "UPDATE pengaduan SET status = ? WHERE id_pengaduan = ?";
        java.sql.PreparedStatement pst2 = conn.prepareStatement(sqlStatus);
        pst2.setString(1, cmb_status.getSelectedItem().toString());
        pst2.setString(2, txt_id.getText());
        pst2.execute();

        JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui!");
        tampil_tabel();
        bersih();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Update: Periksa kembali data Anda.");
    }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
        int row = tabel_pengaduan.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
        return;
    }

    String id = tabel_pengaduan.getValueAt(row, 0).toString();
    String nik = tabel_pengaduan.getValueAt(row, 1).toString();
    String nama = tabel_pengaduan.getValueAt(row, 2).toString();
    String tanggal = tabel_pengaduan.getValueAt(row, 3).toString();
    String isi = tabel_pengaduan.getValueAt(row, 4).toString();
    String kategori = tabel_pengaduan.getValueAt(row, 5).toString();
    String fotoPath = tabel_pengaduan.getValueAt(row, 6).toString();
    String status = tabel_pengaduan.getValueAt(row, 7).toString();

    // PANEL UTAMA
    JPanel panel = new JPanel(new BorderLayout(10, 10));

    // ================= TEKS =================
    JTextArea txt = new JTextArea(
        "ID       : " + id + "\n" +
        "NIK/NISN : " + nik + "\n" +
        "Nama     : " + nama + "\n" +
        "Tanggal  : " + tanggal + "\n" +
        "Kategori : " + kategori + "\n" +
        "Status   : " + status + "\n\n" +
        "Isi Pengaduan:\n" + isi
    );
    txt.setEditable(false);
    txt.setLineWrap(true);
    txt.setWrapStyleWord(true);

    JScrollPane scrollText = new JScrollPane(txt);
    scrollText.setPreferredSize(new Dimension(300, 200));

    // ================= GAMBAR =================
    JLabel lblFoto = new JLabel();
    lblFoto.setHorizontalAlignment(JLabel.CENTER);
    lblFoto.setPreferredSize(new Dimension(200, 250));

    try {
        ImageIcon icon = new ImageIcon(fotoPath);
        Image img = icon.getImage().getScaledInstance(
                200, 250, Image.SCALE_SMOOTH);
        lblFoto.setIcon(new ImageIcon(img));
    } catch (Exception e) {
        lblFoto.setText("Gambar tidak ditemukan");
    }

    // ================= GABUNG PANEL =================
    panel.add(scrollText, BorderLayout.CENTER);
    panel.add(lblFoto, BorderLayout.EAST);

    JOptionPane.showMessageDialog(
        this,
        panel,
        "Detail Pengaduan",
        JOptionPane.INFORMATION_MESSAGE
    );
            // TODO add your handling code here:
    }//GEN-LAST:event_detailActionPerformed

    private void tabel_tanggapanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_tanggapanMouseClicked
    int baris = tabel_pengaduan.getSelectedRow();
    if (baris == -1) return; // kalau belum pilih baris

    try {

        // ================= BASIC DATA =================
        txt_id.setText(
            tabel_pengaduan.getValueAt(baris, 0) != null ?
            tabel_pengaduan.getValueAt(baris, 0).toString() : ""
        );

        txt_NIK.setText(
            tabel_pengaduan.getValueAt(baris, 1) != null ?
            tabel_pengaduan.getValueAt(baris, 1).toString() : ""
        );

        txt_nama.setText(
            tabel_pengaduan.getValueAt(baris, 2) != null ?
            tabel_pengaduan.getValueAt(baris, 2).toString() : ""
        );

        txt_pengaduan.setText(
            tabel_pengaduan.getValueAt(baris, 4) != null ?
            tabel_pengaduan.getValueAt(baris, 4).toString() : ""
        );

        // ================= TANGGAL =================
        if (tabel_pengaduan.getValueAt(baris, 3) != null) {
            String s = tabel_pengaduan.getValueAt(baris, 3).toString();
            java.util.Date date =
                new java.text.SimpleDateFormat("yyyy-MM-dd").parse(s);
            txt_tgl.setDate(date);
        } else {
            txt_tgl.setDate(null);
        }

        // ================= STATUS =================
        if (tabel_pengaduan.getValueAt(baris, 7) != null) {
            String status_tabel =
                tabel_pengaduan.getValueAt(baris, 7).toString();
            cmb_status.setSelectedItem(status_tabel);
        }

        // ================= FOTO =================
        if (tabel_pengaduan.getValueAt(baris, 6) != null) {
            String foto =
                tabel_pengaduan.getValueAt(baris, 6).toString();

            if (!foto.equals("")) {
                ImageIcon icon = new ImageIcon(foto);
                Image img = icon.getImage().getScaledInstance(
                        jLabel8.getWidth(),
                        jLabel8.getHeight(),
                        Image.SCALE_SMOOTH
                );
                jLabel8.setIcon(new ImageIcon(img));
            } else {
                jLabel8.setIcon(null);
            }
        } else {
            jLabel8.setIcon(null);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,
            "Gagal mengambil data tabel: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_tanggapanMouseClicked

    private void lokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lokasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TanggapanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TanggapanAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_refrest;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JComboBox<String> cmb_kategori;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JButton detail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lokasi;
    private javax.swing.JTable tabel_pengaduan;
    private javax.swing.JTable tabel_tanggapan;
    private javax.swing.JTextField txt_NIK;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextArea txt_pengaduan;
    private javax.swing.JTextArea txt_tanggapan;
    private com.toedter.calendar.JDateChooser txt_tgl;
    private com.toedter.calendar.JDateChooser txt_tglpengaduan;
    // End of variables declaration//GEN-END:variables

}
